using CrossBuy.Models.Context;
using CrossBuy.Models.Context.Tasks;
using Microsoft.EntityFrameworkCore;

namespace CrossBuy.BL
{
	// TM-8: read-only reporting. Every method AGGREGATES existing data (tasks + timesheet + links) — writes NO GL/stock.
	public class TaskStatusSummary { public int New { get; set; } public int InProgress { get; set; } public int Done { get; set; } public int Overdue { get; set; } public int Total { get; set; } }
	public class OverdueTaskRow { public int Id { get; set; } public string Title { get; set; } = ""; public string Assignee { get; set; } = ""; public DateTime Due { get; set; } public int DaysLate { get; set; } public string Priority { get; set; } = ""; }
	public class ProductivityRow { public int EmployeeId { get; set; } public string Employee { get; set; } = ""; public decimal Hours { get; set; } public int Completed { get; set; } public int Open { get; set; } }
	public class CostRow { public int RefId { get; set; } public string RefLabel { get; set; } = ""; public decimal Hours { get; set; } public decimal Cost { get; set; } }
	public class BillableCustomerRow { public int CustomerId { get; set; } public string Customer { get; set; } = ""; public decimal Hours { get; set; } public decimal Amount { get; set; } }
	public class AutoTaskRow { public string RuleKey { get; set; } = ""; public int TaskId { get; set; } public string Title { get; set; } = ""; public string Status { get; set; } = ""; public DateTime CreatedAt { get; set; } }

	public interface ITaskReportService
	{
		Task<(TaskStatusSummary mine, TaskStatusSummary team)> SummaryAsync(int companyId, int currentEmployeeId);
		Task<List<OverdueTaskRow>> OverdueAsync(int companyId);
		Task<List<ProductivityRow>> ProductivityAsync(int companyId, DateTime from, DateTime to);
		Task<List<CostRow>> CostByAsync(int companyId, string entityType);
		Task<List<BillableCustomerRow>> BillableByCustomerAsync(int companyId);
		Task<List<AutoTaskRow>> AutoGeneratedAsync(int companyId);
	}

	public class TaskReportService : ITaskReportService
	{
		private readonly CrossDbContext _db;
		private readonly IEmployeeCostService _cost;
		public TaskReportService(CrossDbContext db, IEmployeeCostService cost) { _db = db; _cost = cost; }

		public async Task<(TaskStatusSummary, TaskStatusSummary)> SummaryAsync(int companyId, int currentEmployeeId)
		{
			var now = DateTime.Now;
			var all = await _db.TaskItems.AsNoTracking().Where(t => t.CompanyId == companyId).Select(t => new { t.Status, t.DueDate, t.AssigneeEmployeeId }).ToListAsync();
			TaskStatusSummary Build(List<(string Status, DateTime? Due)> l) => new TaskStatusSummary
			{
				New = l.Count(x => x.Status == "New"),
				InProgress = l.Count(x => x.Status == "InProgress"),
				Done = l.Count(x => x.Status == "Done"),
				Overdue = l.Count(x => x.Due != null && x.Due < now && x.Status != "Done"),
				Total = l.Count
			};
			var mineL = all.Where(x => x.AssigneeEmployeeId == currentEmployeeId).Select(x => (x.Status, x.DueDate)).ToList();
			var teamL = all.Select(x => (x.Status, x.DueDate)).ToList();
			return (Build(mineL), Build(teamL));
		}

		public async Task<List<OverdueTaskRow>> OverdueAsync(int companyId)
		{
			var now = DateTime.Now;
			var rows = await _db.TaskItems.AsNoTracking().Where(t => t.CompanyId == companyId && t.DueDate != null && t.DueDate < now && t.Status != "Done")
				.OrderBy(t => t.DueDate).Select(t => new { t.ID, t.Title, t.AssigneeEmployeeId, t.DueDate, t.Priority }).ToListAsync();
			var names = await NamesAsync(rows.Select(r => r.AssigneeEmployeeId));
			return rows.Select(r => new OverdueTaskRow { Id = r.ID, Title = r.Title, Assignee = names.GetValueOrDefault(r.AssigneeEmployeeId, ""), Due = r.DueDate!.Value, DaysLate = (int)(now.Date - r.DueDate!.Value.Date).TotalDays, Priority = r.Priority }).ToList();
		}

		public async Task<List<ProductivityRow>> ProductivityAsync(int companyId, DateTime from, DateTime to)
		{
			var f = from.Date; var tEnd = to.Date.AddDays(1);
			var hours = (await _db.TimesheetEntries.AsNoTracking().Where(e => e.CompanyId == companyId && e.Hours > 0 && e.WorkDate >= f && e.WorkDate < tEnd)
				.GroupBy(e => e.EmployeeId).Select(g => new { g.Key, H = g.Sum(x => x.Hours) }).ToListAsync()).ToDictionary(x => x.Key, x => x.H);
			var completed = (await _db.TaskItems.AsNoTracking().Where(t => t.CompanyId == companyId && t.CompletedAt != null && t.CompletedAt >= f && t.CompletedAt < tEnd)
				.GroupBy(t => t.AssigneeEmployeeId).Select(g => new { g.Key, C = g.Count() }).ToListAsync()).ToDictionary(x => x.Key, x => x.C);
			var open = (await _db.TaskItems.AsNoTracking().Where(t => t.CompanyId == companyId && t.Status != "Done")
				.GroupBy(t => t.AssigneeEmployeeId).Select(g => new { g.Key, O = g.Count() }).ToListAsync()).ToDictionary(x => x.Key, x => x.O);
			var empIds = hours.Keys.Union(completed.Keys).Union(open.Keys).Where(id => id > 0).Distinct().ToList();
			var names = await NamesAsync(empIds);
			return empIds.Select(id => new ProductivityRow { EmployeeId = id, Employee = names.GetValueOrDefault(id, ""), Hours = hours.GetValueOrDefault(id, 0m), Completed = completed.GetValueOrDefault(id, 0), Open = open.GetValueOrDefault(id, 0) })
				.OrderByDescending(r => r.Hours).ToList();
		}

		public async Task<List<CostRow>> CostByAsync(int companyId, string entityType)
		{
			// tasks linked to this entity type → per entity, Σ (hours × employee hourly cost)
			var tasks = await _db.TaskItems.AsNoTracking().Where(t => t.CompanyId == companyId && t.EntityType == entityType && t.EntityId != null)
				.Select(t => new { t.ID, EntId = t.EntityId!.Value }).ToListAsync();
			if (tasks.Count == 0) return new();
			var taskToEnt = tasks.ToDictionary(t => t.ID, t => t.EntId);
			var taskIds = tasks.Select(t => t.ID).ToList();
			var entries = await _db.TimesheetEntries.AsNoTracking().Where(e => e.CompanyId == companyId && taskIds.Contains(e.TaskId) && e.Hours > 0).Select(e => new { e.TaskId, e.EmployeeId, e.Hours }).ToListAsync();
			// rate cache
			var rateCache = new Dictionary<int, decimal>();
			async Task<decimal> Rate(int emp) { if (!rateCache.TryGetValue(emp, out var r)) { r = await _cost.HourlyCostAsync(companyId, emp); rateCache[emp] = r; } return r; }
			var byEnt = new Dictionary<int, (decimal hours, decimal cost)>();
			foreach (var e in entries)
			{
				var ent = taskToEnt[e.TaskId];
				var rate = await Rate(e.EmployeeId);
				var cur = byEnt.GetValueOrDefault(ent, (0m, 0m));
				byEnt[ent] = (cur.Item1 + e.Hours, cur.Item2 + Math.Round(e.Hours * rate, 2));
			}
			var labels = await LabelsAsync(entityType, byEnt.Keys.ToList(), companyId);
			return byEnt.Select(kv => new CostRow { RefId = kv.Key, RefLabel = labels.GetValueOrDefault(kv.Key, "#" + kv.Key), Hours = kv.Value.Item1, Cost = kv.Value.Item2 }).OrderByDescending(r => r.Cost).ToList();
		}

		public async Task<List<BillableCustomerRow>> BillableByCustomerAsync(int companyId)
		{
			var tasks = await _db.TaskItems.AsNoTracking().Where(t => t.CompanyId == companyId && t.IsBillable && t.CustomerId != null && t.BillRate != null)
				.Select(t => new { t.ID, Cust = t.CustomerId!.Value, Rate = t.BillRate!.Value }).ToListAsync();
			if (tasks.Count == 0) return new();
			var taskIds = tasks.Select(t => t.ID).ToList();
			var uninv = (await _db.TimesheetEntries.AsNoTracking().Where(e => e.CompanyId == companyId && taskIds.Contains(e.TaskId) && e.Hours > 0 && e.InvoicedInvoiceId == null)
				.GroupBy(e => e.TaskId).Select(g => new { g.Key, H = g.Sum(x => x.Hours) }).ToListAsync()).ToDictionary(x => x.Key, x => x.H);
			var byCust = new Dictionary<int, (decimal hours, decimal amount)>();
			foreach (var t in tasks)
			{
				var h = uninv.GetValueOrDefault(t.ID, 0m); if (h <= 0) continue;
				var cur = byCust.GetValueOrDefault(t.Cust, (0m, 0m));
				byCust[t.Cust] = (cur.Item1 + h, cur.Item2 + Math.Round(h * t.Rate, 2));
			}
			var isEn = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName != "ar";
			var names = (await _db.Customers.AsNoTracking().Where(c => byCust.Keys.Contains(c.ID)).Select(c => new { c.ID, c.Name, c.NameEn }).ToListAsync())
				.ToDictionary(c => c.ID, c => ((isEn && !string.IsNullOrWhiteSpace(c.NameEn)) ? c.NameEn : c.Name) ?? "");
			return byCust.Select(kv => new BillableCustomerRow { CustomerId = kv.Key, Customer = names.GetValueOrDefault(kv.Key, "#" + kv.Key), Hours = kv.Value.Item1, Amount = kv.Value.Item2 }).OrderByDescending(r => r.Amount).ToList();
		}

		public async Task<List<AutoTaskRow>> AutoGeneratedAsync(int companyId)
		{
			var rows = await (from l in _db.TaskAutoLogs.AsNoTracking().Where(l => l.CompanyId == companyId)
							  join t in _db.TaskItems.AsNoTracking() on l.TaskId equals t.ID into tj
							  from t in tj.DefaultIfEmpty()
							  orderby l.CreatedAt descending
							  select new AutoTaskRow { RuleKey = l.RuleKey, TaskId = l.TaskId, Title = t != null ? t.Title : "—", Status = t != null ? t.Status : "—", CreatedAt = l.CreatedAt }).Take(500).ToListAsync();
			return rows;
		}

		private async Task<Dictionary<int, string>> NamesAsync(IEnumerable<int> ids)
		{
			var list = ids.Where(i => i > 0).Distinct().ToList();
			if (list.Count == 0) return new();
			var isEn = System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName != "ar";
			var rows = await _db.Employee.AsNoTracking().Where(e => list.Contains(e.ID)).Select(e => new { e.ID, e.FullName, e.FullNameEn }).ToListAsync();
			return rows.ToDictionary(e => e.ID, e => ((isEn && !string.IsNullOrWhiteSpace(e.FullNameEn)) ? e.FullNameEn : e.FullName) ?? "");
		}
		private async Task<Dictionary<int, string>> LabelsAsync(string entityType, List<int> ids, int companyId)
		{
			if (ids.Count == 0) return new();
			if (entityType == "Project")
				return await _db.Projects.AsNoTracking().Where(p => p.CompanyID == companyId && ids.Contains(p.ID)).ToDictionaryAsync(p => p.ID, p => p.Code + " — " + p.Name);
			if (entityType == "ManufWorkOrder")
				return await _db.ManufWorkOrders.AsNoTracking().Where(w => w.CompanyID == companyId && ids.Contains(w.ID)).ToDictionaryAsync(w => w.ID, w => w.WoNo ?? ("#" + w.ID));
			return new();
		}
	}
}
