using System.Text.Json;
using CrossBuy.Models.Platform;

namespace CrossBuy.BL.Platform.Ai
{
    // AI Foundation — Increment 4.10. THE SYNTHETIC SMOKE-TEST PAYLOAD, AND THE GUARD THAT PROVES IT.
    //
    // WHY THIS EXISTS. The owner recorded a development constraint: if CrossBuy ever performs a
    // controlled OpenAI Development smoke test, the content must be **fully synthetic** — no personal
    // data, no customer, vendor or employee names, no real invoice numbers, no free-text business
    // content, nothing read from any database, and no credentials. Written down, that is a promise.
    // Written here, it is a check.
    //
    // THE ATTACK THIS CLOSES. `AiDataClassification.SyntheticTestData` is a label, and a label is
    // self-asserted. Without a guard, relabelling a payload of real journal descriptions as "synthetic"
    // would walk it straight past the classification matrix, which refuses FreeTextBusinessContent at
    // every external destination. So the label alone is worth nothing: the adapter requires the payload
    // to actually BE the synthetic payload, and this type is the only thing that can produce one.
    //
    // ALLOWLIST, NOT DENYLIST, AND THAT ORDER MATTERS. It would be easier to scan for the things that are
    // forbidden — an "@", a long digit run, a name-shaped word. Every such scan is a guess about what
    // real data looks like, and real data is under no obligation to look like the guess. Instead the
    // payload must match a FIXED, CLOSED shape: an exact set of property names, each with a value drawn
    // from a fixed set. Anything else — an extra property, a changed string, a nested object — fails.
    // A denylist has to imagine every leak; an allowlist only has to describe one payload.
    //
    // NO DATABASE, NO CONFIGURATION, NO CLOCK, NO RANDOMNESS. The builder is a pure function of nothing.
    // It takes no DbContext, no connection string, no IConfiguration and no caller-supplied content, so
    // there is no parameter through which real data could arrive — the guarantee is structural rather
    // than a rule someone has to remember. It is also DETERMINISTIC: the same bytes every time, which is
    // what lets the guard compare against a constant instead of re-deriving a shape.
    public static class AiSyntheticPayload
    {
        /// The obviously-fake company marker. Not a real company, not a company id, not resolvable.
        public const string Company = "SYNTHETIC-CROSSBUY-TEST";

        /// Names the one scenario this payload exists for, so an audit row says why it was ever sent.
        public const string Scenario = "OPENAI-DEVELOPMENT-SMOKE-TEST";

        /// A value that is unmistakably a placeholder and could not be a real balance.
        public const decimal Amount = 123.45m;

        /// A fixed currency code. Present so the payload is well-formed for a forecast prompt, not
        /// because any currency is being modelled.
        public const string Currency = "XTS";   // ISO 4217's own "reserved for testing" code.

        /// The classification a synthetic payload must be sent under, stated once so the adapter, the
        /// caller and the tests cannot disagree about it.
        public const AiDataClassification Classification = AiDataClassification.SyntheticTestData;

        /// <summary>The exact JSON, byte for byte, every time.</summary>
        /// <remarks>
        /// Property order is fixed and the values are compile-time constants, so this is a constant in
        /// everything but syntax. <see cref="IsSynthetic"/> compares against it after re-serialising the
        /// candidate, which means formatting differences are tolerated and content differences are not.
        /// </remarks>
        public static string Build() => JsonSerializer.Serialize(new SyntheticShape
        {
            company = Company,
            scenario = Scenario,
            amount = Amount,
            currency = Currency,
            note = "Synthetic content generated by CrossBuy for a provider connectivity check. " +
                   "It describes no person, no customer, no vendor and no transaction.",
        });

        /// <summary>True only for the exact payload <see cref="Build"/> produces.</summary>
        /// <remarks>
        /// <para>
        /// Deliberately strict in three ways at once. The JSON must PARSE — an unparseable payload is not
        /// a synthetic payload, whatever it contains. It must carry EXACTLY the five known properties —
        /// `JsonSerializer` with <c>UnmappedMemberHandling.Disallow</c> rejects a sixth, which is where a
        /// smuggled field would go. And every value must EQUAL the constant above — which is what stops
        /// the shape being reused as an envelope for something else.
        /// </para>
        /// <para>
        /// Returns false rather than throwing, on every path. This runs inside a send decision, and a
        /// guard that can throw turns a refusal into an unhandled error at exactly the moment the caller
        /// is trying to reach a provider.
        /// </para>
        /// </remarks>
        public static bool IsSynthetic(string? payloadJson)
        {
            if (string.IsNullOrWhiteSpace(payloadJson)) return false;

            // A generous but finite bound. The real payload is a few hundred bytes; anything far larger
            // is not it, and refusing early keeps a hostile input away from the parser.
            if (payloadJson.Length > 4096) return false;

            SyntheticShape? parsed;
            try
            {
                parsed = JsonSerializer.Deserialize<SyntheticShape>(payloadJson, StrictOptions);
            }
            catch (JsonException)
            {
                return false;
            }

            if (parsed is null) return false;

            return string.Equals(parsed.company, Company, StringComparison.Ordinal)
                   && string.Equals(parsed.scenario, Scenario, StringComparison.Ordinal)
                   && parsed.amount == Amount
                   && string.Equals(parsed.currency, Currency, StringComparison.Ordinal)
                   && string.Equals(parsed.note, NoteOf(Build()), StringComparison.Ordinal);
        }

        private static readonly JsonSerializerOptions StrictOptions = new()
        {
            // The sixth-property defence. Without it an attacker-supplied field would be silently
            // dropped by the deserialiser and the payload would compare equal on the five it does know.
            UnmappedMemberHandling = System.Text.Json.Serialization.JsonUnmappedMemberHandling.Disallow,
            PropertyNameCaseInsensitive = false,
        };

        /// Reads the note back out of the canonical payload rather than duplicating the literal, so the
        /// builder stays the single definition of what the note says.
        private static string NoteOf(string canonical)
            => JsonSerializer.Deserialize<SyntheticShape>(canonical, StrictOptions)!.note!;

        // Lower-case member names because they are the WIRE FORMAT, not C# properties — the JSON a
        // reviewer reads in an audit trail should be the JSON this class describes, with no serializer
        // naming policy in between to reason about.
#pragma warning disable IDE1006 // Naming rule violation: wire-format member names, intentional.
        private sealed class SyntheticShape
        {
            public string? company { get; set; }
            public string? scenario { get; set; }
            public decimal amount { get; set; }
            public string? currency { get; set; }
            public string? note { get; set; }
        }
#pragma warning restore IDE1006
    }
}
