//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossBuy.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrossBuy.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbsenceDaysBeforePenalty.
        /// </summary>
        public static string AbsenceDaysBeforePenalty {
            get {
                return ResourceManager.GetString("AbsenceDaysBeforePenalty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbsenceDeductionPerDay.
        /// </summary>
        public static string AbsenceDeductionPerDay {
            get {
                return ResourceManager.GetString("AbsenceDeductionPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Edit Leave Type.
        /// </summary>
        public static string AddEditLeaveType {
            get {
                return ResourceManager.GetString("AddEditLeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding an administrative body to the administrative structure.
        /// </summary>
        public static string AddingAnAdministrativeBodyToTheAdministrativeStructure {
            get {
                return ResourceManager.GetString("AddingAnAdministrativeBodyToTheAdministrativeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Bodies in the Company.
        /// </summary>
        public static string AdministrativeBodiesIntheCompany {
            get {
                return ResourceManager.GetString("AdministrativeBodiesIntheCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrative Structure.
        /// </summary>
        public static string AdministrativeStructure {
            get {
                return ResourceManager.GetString("AdministrativeStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow During Working Hours.
        /// </summary>
        public static string AllowDuringWorkingHours {
            get {
                return ResourceManager.GetString("AllowDuringWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowEarlyCheckOut.
        /// </summary>
        public static string AllowEarlyCheckOut {
            get {
                return ResourceManager.GetString("AllowEarlyCheckOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Late Check-in.
        /// </summary>
        public static string AllowLateCheckIn {
            get {
                return ResourceManager.GetString("AllowLateCheckIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Week.
        /// </summary>
        public static string AllWeek {
            get {
                return ResourceManager.GetString("AllWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string AM {
            get {
                return ResourceManager.GetString("AM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AmountsAndAllowances.
        /// </summary>
        public static string AmountsAndAllowances {
            get {
                return ResourceManager.GetString("AmountsAndAllowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annual Leave Entitlement.
        /// </summary>
        public static string AnnualLeaveEntitlement {
            get {
                return ResourceManager.GetString("AnnualLeaveEntitlement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicableInsuranceAndTaxRates.
        /// </summary>
        public static string ApplicableInsuranceAndTaxRates {
            get {
                return ResourceManager.GetString("ApplicableInsuranceAndTaxRates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Required.
        /// </summary>
        public static string ApprovalRequired {
            get {
                return ResourceManager.GetString("ApprovalRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attach files.
        /// </summary>
        public static string AttachFiles {
            get {
                return ResourceManager.GetString("AttachFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View attachment.
        /// </summary>
        public static string AttachmentView {
            get {
                return ResourceManager.GetString("AttachmentView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment name.
        /// </summary>
        public static string AttachName {
            get {
                return ResourceManager.GetString("AttachName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicInformation.
        /// </summary>
        public static string BasicInformation {
            get {
                return ResourceManager.GetString("BasicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicSalary.
        /// </summary>
        public static string BasicSalary {
            get {
                return ResourceManager.GetString("BasicSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BasicSalaryAndMonthlyAllowances.
        /// </summary>
        public static string BasicSalaryAndMonthlyAllowances {
            get {
                return ResourceManager.GetString("BasicSalaryAndMonthlyAllowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Data.
        /// </summary>
        public static string BranchData {
            get {
                return ResourceManager.GetString("BranchData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branches.
        /// </summary>
        public static string Branches {
            get {
                return ResourceManager.GetString("Branches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch name.
        /// </summary>
        public static string BranchName {
            get {
                return ResourceManager.GetString("BranchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name Arabic.
        /// </summary>
        public static string BranchNameAr {
            get {
                return ResourceManager.GetString("BranchNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch Name English.
        /// </summary>
        public static string BranchNameEn {
            get {
                return ResourceManager.GetString("BranchNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreakDurationMinutes.
        /// </summary>
        public static string BreakDurationMinutes {
            get {
                return ResourceManager.GetString("BreakDurationMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreakEndTime.
        /// </summary>
        public static string BreakEndTime {
            get {
                return ResourceManager.GetString("BreakEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreakStartTime.
        /// </summary>
        public static string BreakStartTime {
            get {
                return ResourceManager.GetString("BreakStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreakTime.
        /// </summary>
        public static string BreakTime {
            get {
                return ResourceManager.GetString("BreakTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BreakTimeNote.
        /// </summary>
        public static string BreakTimeNote {
            get {
                return ResourceManager.GetString("BreakTimeNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carry Forward Limit.
        /// </summary>
        public static string CarryForwardLimit {
            get {
                return ResourceManager.GetString("CarryForwardLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Carry Over Limit.
        /// </summary>
        public static string CarryOverLimit {
            get {
                return ResourceManager.GetString("CarryOverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Item.
        /// </summary>
        public static string ChooseItem {
            get {
                return ResourceManager.GetString("ChooseItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies.
        /// </summary>
        public static string Companies {
            get {
                return ResourceManager.GetString("Companies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies List.
        /// </summary>
        public static string CompaniesList {
            get {
                return ResourceManager.GetString("CompaniesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Data.
        /// </summary>
        public static string CompanyData {
            get {
                return ResourceManager.GetString("CompanyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Logo.
        /// </summary>
        public static string CompanyLogo {
            get {
                return ResourceManager.GetString("CompanyLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Name .
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name arabic.
        /// </summary>
        public static string CompanyNameAr {
            get {
                return ResourceManager.GetString("CompanyNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name english.
        /// </summary>
        public static string CompanyNameEn {
            get {
                return ResourceManager.GetString("CompanyNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whether the company is listed below another owner company according to the same system.
        /// </summary>
        public static string companySub {
            get {
                return ResourceManager.GetString("companySub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company Type.
        /// </summary>
        public static string CompanyType {
            get {
                return ResourceManager.GetString("CompanyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string Complete {
            get {
                return ResourceManager.GetString("Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to modify the data?.
        /// </summary>
        public static string ConfirmMSG {
            get {
                return ResourceManager.GetString("ConfirmMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control Panel.
        /// </summary>
        public static string ControlPanel {
            get {
                return ResourceManager.GetString("ControlPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Short Leave Limit.
        /// </summary>
        public static string DailyhortLeaveLimit {
            get {
                return ResourceManager.GetString("DailyhortLeaveLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days/Year.
        /// </summary>
        public static string Days_Year {
            get {
                return ResourceManager.GetString("Days/Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deduction on Limit Exceeded.
        /// </summary>
        public static string DeductionOnLimitExceeded {
            get {
                return ResourceManager.GetString("DeductionOnLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EarningsAndDeductions.
        /// </summary>
        public static string EarningsAndDeductions {
            get {
                return ResourceManager.GetString("EarningsAndDeductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeInsuranceContribution.
        /// </summary>
        public static string EmployeeInsuranceContribution {
            get {
                return ResourceManager.GetString("EmployeeInsuranceContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeSocialInsurance.
        /// </summary>
        public static string EmployeeSocialInsurance {
            get {
                return ResourceManager.GetString("EmployeeSocialInsurance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployerInsuranceContribution.
        /// </summary>
        public static string EmployerInsuranceContribution {
            get {
                return ResourceManager.GetString("EmployerInsuranceContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Short Leave.
        /// </summary>
        public static string EnableShortLeave {
            get {
                return ResourceManager.GetString("EnableShortLeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entitlement Days Per Year.
        /// </summary>
        public static string EntitlementDaysPerYear {
            get {
                return ResourceManager.GetString("EntitlementDaysPerYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exempt.
        /// </summary>
        public static string Exempt {
            get {
                return ResourceManager.GetString("Exempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max file size is 1MB and max number of files is 5..
        /// </summary>
        public static string File_size {
            get {
                return ResourceManager.GetString("File_size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Required Fields.
        /// </summary>
        public static string FillRequiredFields {
            get {
                return ResourceManager.GetString("FillRequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill Required Fields ForParent Company.
        /// </summary>
        public static string FillRequiredFieldsForParentCompany {
            get {
                return ResourceManager.GetString("FillRequiredFieldsForParentCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Financial statements.
        /// </summary>
        public static string Financialٍstatements {
            get {
                return ResourceManager.GetString("Financialٍstatements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GraceMinutes.
        /// </summary>
        public static string GraceMinutes {
            get {
                return ResourceManager.GetString("GraceMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HousingAllowance.
        /// </summary>
        public static string HousingAllowance {
            get {
                return ResourceManager.GetString("HousingAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IncomeTax.
        /// </summary>
        public static string IncomeTax {
            get {
                return ResourceManager.GetString("IncomeTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Data.
        /// </summary>
        public static string IncompleteData {
            get {
                return ResourceManager.GetString("IncompleteData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IntegrateShortLeavewithBiometricAttendance.
        /// </summary>
        public static string IntegrateShortLeavewithBiometricAttendance {
            get {
                return ResourceManager.GetString("IntegrateShortLeavewithBiometricAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interactive Summary.
        /// </summary>
        public static string InteractiveSummary {
            get {
                return ResourceManager.GetString("InteractiveSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username or password is incorrect!.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title.
        /// </summary>
        public static string JobTitle {
            get {
                return ResourceManager.GetString("JobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title - Arabic.
        /// </summary>
        public static string JobTitleArabic {
            get {
                return ResourceManager.GetString("JobTitleArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title Data.
        /// </summary>
        public static string JobTitleData {
            get {
                return ResourceManager.GetString("JobTitleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Title - English.
        /// </summary>
        public static string JobTitleEnglish {
            get {
                return ResourceManager.GetString("JobTitleEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Titles List.
        /// </summary>
        public static string JobTitleList {
            get {
                return ResourceManager.GetString("JobTitleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lateness and Deductions.
        /// </summary>
        public static string LatenessAndDeductions {
            get {
                return ResourceManager.GetString("LatenessAndDeductions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatenessDeductionPerMinute.
        /// </summary>
        public static string LatenessDeductionPerMinute {
            get {
                return ResourceManager.GetString("LatenessDeductionPerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LatenessDeductionRate.
        /// </summary>
        public static string LatenessDeductionRate {
            get {
                return ResourceManager.GetString("LatenessDeductionRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late Occurrences Before Warning.
        /// </summary>
        public static string LateOccurrencesBeforeWarning {
            get {
                return ResourceManager.GetString("LateOccurrencesBeforeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Name.
        /// </summary>
        public static string LeaveName {
            get {
                return ResourceManager.GetString("LeaveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Permission.
        /// </summary>
        public static string LeavePermission {
            get {
                return ResourceManager.GetString("LeavePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeavePolicesList.
        /// </summary>
        public static string LeavePolicesList {
            get {
                return ResourceManager.GetString("LeavePolicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeavePolicy.
        /// </summary>
        public static string LeavePolicy {
            get {
                return ResourceManager.GetString("LeavePolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeaveType.
        /// </summary>
        public static string LeaveType {
            get {
                return ResourceManager.GetString("LeaveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Type and Entitlement Details.
        /// </summary>
        public static string LeaveTypeAndEntitlementDetails {
            get {
                return ResourceManager.GetString("LeaveTypeAndEntitlementDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Administrative Bodies in the Company.
        /// </summary>
        public static string ListOfAdministrativeBodiesInTheCompany {
            get {
                return ResourceManager.GetString("ListOfAdministrativeBodiesInTheCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Of Branches.
        /// </summary>
        public static string ListOfBranches {
            get {
                return ResourceManager.GetString("ListOfBranches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main policy data.
        /// </summary>
        public static string MainPolicyData {
            get {
                return ResourceManager.GetString("MainPolicyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Managing company.
        /// </summary>
        public static string ManagingCompany {
            get {
                return ResourceManager.GetString("ManagingCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Daily Duration.
        /// </summary>
        public static string MaximumDailyDuration {
            get {
                return ResourceManager.GetString("MaximumDailyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Monthly Duration.
        /// </summary>
        public static string MaximumMonthlyDuration {
            get {
                return ResourceManager.GetString("MaximumMonthlyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Weekly Duration.
        /// </summary>
        public static string MaximumWeeklyDuration {
            get {
                return ResourceManager.GetString("MaximumWeeklyDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Certificate Required.
        /// </summary>
        public static string MedicalCertificateRequired {
            get {
                return ResourceManager.GetString("MedicalCertificateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minute.
        /// </summary>
        public static string Minute {
            get {
                return ResourceManager.GetString("Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Short Leave Limit.
        /// </summary>
        public static string MonthlyShortLeaveLimit {
            get {
                return ResourceManager.GetString("MonthlyShortLeaveLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Arabic.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name English.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the administrative body - Arabic.
        /// </summary>
        public static string NameOfTheAdministrativeBodyArabic {
            get {
                return ResourceManager.GetString("NameOfTheAdministrativeBodyArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the administrative body - English.
        /// </summary>
        public static string NameOfTheAdministrativeBodyEnglish {
            get {
                return ResourceManager.GetString("NameOfTheAdministrativeBodyEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the primary administrative body - Arabic.
        /// </summary>
        public static string NameOfThePrimaryAdministrativeBodyArabic {
            get {
                return ResourceManager.GetString("NameOfThePrimaryAdministrativeBodyArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the primary administrative body - English.
        /// </summary>
        public static string NameOfThePrimaryAdministrativeBodyEnglish {
            get {
                return ResourceManager.GetString("NameOfThePrimaryAdministrativeBodyEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Leaves Added.
        /// </summary>
        public static string NoLeavesAdded {
            get {
                return ResourceManager.GetString("NoLeavesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Period (Days).
        /// </summary>
        public static string NoticePeriod {
            get {
                return ResourceManager.GetString("NoticePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notice Period Days.
        /// </summary>
        public static string NoticePeriodDays {
            get {
                return ResourceManager.GetString("NoticePeriodDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Required.
        /// </summary>
        public static string NotRequired {
            get {
                return ResourceManager.GetString("NotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official Working Hours.
        /// </summary>
        public static string OfficialWorkingHours {
            get {
                return ResourceManager.GetString("OfficialWorkingHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtherAllowances.
        /// </summary>
        public static string OtherAllowances {
            get {
                return ResourceManager.GetString("OtherAllowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OvertimeLatenessAndAbsence.
        /// </summary>
        public static string OvertimeLatenessAndAbsence {
            get {
                return ResourceManager.GetString("OvertimeLatenessAndAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overtime Rate.
        /// </summary>
        public static string OvertimeRate {
            get {
                return ResourceManager.GetString("OvertimeRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent Compay.
        /// </summary>
        public static string ParentCompay {
            get {
                return ResourceManager.GetString("ParentCompay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayDay.
        /// </summary>
        public static string PayDay {
            get {
                return ResourceManager.GetString("PayDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaymentMethod.
        /// </summary>
        public static string PaymentMethod {
            get {
                return ResourceManager.GetString("PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayrollPolicy.
        /// </summary>
        public static string PayrollPolicy {
            get {
                return ResourceManager.GetString("PayrollPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per.
        /// </summary>
        public static string Per {
            get {
                return ResourceManager.GetString("Per", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait a moment.
        /// </summary>
        public static string PleaseWaitMoment {
            get {
                return ResourceManager.GetString("PleaseWaitMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string PM {
            get {
                return ResourceManager.GetString("PM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policies.
        /// </summary>
        public static string Policies {
            get {
                return ResourceManager.GetString("Policies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy Data Status.
        /// </summary>
        public static string PolicyDataStatus {
            get {
                return ResourceManager.GetString("PolicyDataStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PolicyDescriptionandPaymentMethod.
        /// </summary>
        public static string PolicyDescriptionandPaymentMethod {
            get {
                return ResourceManager.GetString("PolicyDescriptionandPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Request on Limit Exceeded.
        /// </summary>
        public static string RejectRequestOnLimitExceeded {
            get {
                return ResourceManager.GetString("RejectRequestOnLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string RemoveAll {
            get {
                return ResourceManager.GetString("RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the required fields correctly..
        /// </summary>
        public static string RequiredConfirm {
            get {
                return ResourceManager.GetString("RequiredConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred, the data was not saved.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving .....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Leave Deduction Rate Per Minute.
        /// </summary>
        public static string ShortLeaveDeductionRatePerMinute {
            get {
                return ResourceManager.GetString("ShortLeaveDeductionRatePerMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowAll.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single Short Leave Duration.
        /// </summary>
        public static string SingleShortLeaveDuration {
            get {
                return ResourceManager.GetString("SingleShortLeaveDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SocialInsuranceAndTax.
        /// </summary>
        public static string SocialInsuranceAndTax {
            get {
                return ResourceManager.GetString("SocialInsuranceAndTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specific Days.
        /// </summary>
        public static string SpecificDays {
            get {
                return ResourceManager.GetString("SpecificDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsidiary Company?.
        /// </summary>
        public static string SubsidiaryCompany {
            get {
                return ResourceManager.GetString("SubsidiaryCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The data has been saved successfully.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Applicable.
        /// </summary>
        public static string TaxApplicable {
            get {
                return ResourceManager.GetString("TaxApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TaxNotApplicable.
        /// </summary>
        public static string TaxNotApplicable {
            get {
                return ResourceManager.GetString("TaxNotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number.
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Rate.
        /// </summary>
        public static string TaxRate {
            get {
                return ResourceManager.GetString("TaxRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time and Attendance and Deduction Rules.
        /// </summary>
        public static string TimeAndAttendanceandDeductionRules {
            get {
                return ResourceManager.GetString("TimeAndAttendanceandDeductionRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeAttendance.
        /// </summary>
        public static string TimeAttendance {
            get {
                return ResourceManager.GetString("TimeAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalAllowances.
        /// </summary>
        public static string TotalAllowances {
            get {
                return ResourceManager.GetString("TotalAllowances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransportationAllowance.
        /// </summary>
        public static string TransportationAllowance {
            get {
                return ResourceManager.GetString("TransportationAllowance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Types of vacations.
        /// </summary>
        public static string TypesOfLeaves {
            get {
                return ResourceManager.GetString("TypesOfLeaves", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly Short Leave Limit.
        /// </summary>
        public static string WeeklyShortLeaveLimit {
            get {
                return ResourceManager.GetString("WeeklyShortLeaveLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkDaysPerWeek.
        /// </summary>
        public static string WorkDaysPerWeek {
            get {
                return ResourceManager.GetString("WorkDaysPerWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkEndTime.
        /// </summary>
        public static string WorkEndTime {
            get {
                return ResourceManager.GetString("WorkEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkHoursPerDay.
        /// </summary>
        public static string WorkHoursPerDay {
            get {
                return ResourceManager.GetString("WorkHoursPerDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkSchedule.
        /// </summary>
        public static string WorkSchedule {
            get {
                return ResourceManager.GetString("WorkSchedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkScheduleNote.
        /// </summary>
        public static string WorkScheduleNote {
            get {
                return ResourceManager.GetString("WorkScheduleNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkStartTime.
        /// </summary>
        public static string WorkStartTime {
            get {
                return ResourceManager.GetString("WorkStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes/No.
        /// </summary>
        public static string YesNo {
            get {
                return ResourceManager.GetString("YesNo", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInTitle {
            get {
                return ResourceManager.GetString("SignInTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Use your company account.
        /// </summary>
        public static string SignInSubtitle {
            get {
                return ResourceManager.GetString("SignInSubtitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInAction {
            get {
                return ResourceManager.GetString("SignInAction", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Signing in….
        /// </summary>
        public static string SigningIn {
            get {
                return ResourceManager.GetString("SigningIn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Keep me signed in.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot your password? Your system administrator can reset it..
        /// </summary>
        public static string ForgotPasswordHelp {
            get {
                return ResourceManager.GetString("ForgotPasswordHelp", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Show password.
        /// </summary>
        public static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Hide password.
        /// </summary>
        public static string HidePassword {
            get {
                return ResourceManager.GetString("HidePassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Caps Lock is on.
        /// </summary>
        public static string CapsLockOn {
            get {
                return ResourceManager.GetString("CapsLockOn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign-in failed.
        /// </summary>
        public static string SignInFailed {
            get {
                return ResourceManager.GetString("SignInFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        public static string SignInErrorGeneric {
            get {
                return ResourceManager.GetString("SignInErrorGeneric", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to User name is required.
        /// </summary>
        public static string UserNameRequired {
            get {
                return ResourceManager.GetString("UserNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password is required.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to From the purchase order to the journal entry.
        /// </summary>
        public static string LoginHeadline {
            get {
                return ResourceManager.GetString("LoginHeadline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Purchasing, inventory, manufacturing, sales and accounts in one platform —.
        /// </summary>
        public static string LoginPitchLead {
            get {
                return ResourceManager.GetString("LoginPitchLead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to every document posts its own entry.
        /// </summary>
        public static string LoginPitchAccent {
            get {
                return ResourceManager.GetString("LoginPitchAccent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to in Arabic and English..
        /// </summary>
        public static string LoginPitchTail {
            get {
                return ResourceManager.GetString("LoginPitchTail", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to HR.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to THE CROSS-BUSINESS PLATFORM.
        /// </summary>
        public static string BrandTagline {
            get {
                return ResourceManager.GetString("BrandTagline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to One Platform..
        /// </summary>
        public static string BrandHeadlineLead {
            get {
                return ResourceManager.GetString("BrandHeadlineLead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Endless Possibilities..
        /// </summary>
        public static string BrandHeadlineAccent {
            get {
                return ResourceManager.GetString("BrandHeadlineAccent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Connect your people, processes and data..
        /// </summary>
        public static string BrandSubLine1 {
            get {
                return ResourceManager.GetString("BrandSubLine1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Build a smarter tomorrow..
        /// </summary>
        public static string BrandSubLine2 {
            get {
                return ResourceManager.GetString("BrandSubLine2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to BUSINESS WITHOUT BOUNDARIES.
        /// </summary>
        public static string BrandFootline {
            get {
                return ResourceManager.GetString("BrandFootline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string WelcomeBackLead {
            get {
                return ResourceManager.GetString("WelcomeBackLead", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string WelcomeBackAccent {
            get {
                return ResourceManager.GetString("WelcomeBackAccent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign in to your CrossBuy account.
        /// </summary>
        public static string SignInToYourAccount {
            get {
                return ResourceManager.GetString("SignInToYourAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string ForgotPasswordQ {
            get {
                return ResourceManager.GetString("ForgotPasswordQ", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to or continue with.
        /// </summary>
        public static string OrContinueWith {
            get {
                return ResourceManager.GetString("OrContinueWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to New to CrossBuy?.
        /// </summary>
        public static string NewToCrossBuy {
            get {
                return ResourceManager.GetString("NewToCrossBuy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Contact your administrator.
        /// </summary>
        public static string ContactYourAdministrator {
            get {
                return ResourceManager.GetString("ContactYourAdministrator", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to All rights reserved..
        /// </summary>
        public static string AllRightsReserved {
            get {
                return ResourceManager.GetString("AllRightsReserved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Secure.
        /// </summary>
        public static string TrustSecure {
            get {
                return ResourceManager.GetString("TrustSecure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reliable.
        /// </summary>
        public static string TrustReliable {
            get {
                return ResourceManager.GetString("TrustReliable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Scalable.
        /// </summary>
        public static string TrustScalable {
            get {
                return ResourceManager.GetString("TrustScalable", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sign in with {0}.
        /// </summary>
        public static string SignInWith {
            get {
                return ResourceManager.GetString("SignInWith", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to That sign-in did not complete. Please try again..
        /// </summary>
        public static string ExternalSignInFailed {
            get {
                return ResourceManager.GetString("ExternalSignInFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No CrossBuy account is linked to that address. Ask your administrator to create one..
        /// </summary>
        public static string ExternalNoAccount {
            get {
                return ResourceManager.GetString("ExternalNoAccount", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        public static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Inventory.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CRM.
        /// </summary>
        public static string CRM {
            get {
                return ResourceManager.GetString("CRM", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        public static string POS {
            get {
                return ResourceManager.GetString("POS", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Manufacturing.
        /// </summary>
        public static string Manufacturing {
            get {
                return ResourceManager.GetString("Manufacturing", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to Single sign-on is not set up for this installation. Your system administrator can enable it..
        /// </summary>
        public static string ExternalNotConfigured {
            get {
                return ResourceManager.GetString("ExternalNotConfigured", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to PEOPLE.
        /// </summary>
        public static string PillarPeople {
            get {
                return ResourceManager.GetString("PillarPeople", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to TECHNOLOGY.
        /// </summary>
        public static string PillarTechnology {
            get {
                return ResourceManager.GetString("PillarTechnology", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to PROCESSES.
        /// </summary>
        public static string PillarProcesses {
            get {
                return ResourceManager.GetString("PillarProcesses", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to GROWTH.
        /// </summary>
        public static string PillarGrowth {
            get {
                return ResourceManager.GetString("PillarGrowth", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Smarter Business Together.
        /// </summary>
        public static string SmarterBusinessTogether {
            get {
                return ResourceManager.GetString("SmarterBusinessTogether", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        public static string POSShort {
            get {
                return ResourceManager.GetString("POSShort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMeShort {
            get {
                return ResourceManager.GetString("RememberMeShort", resourceCulture);
            }
        }
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LanguageNameEn {
            get {
                return ResourceManager.GetString("LanguageNameEn", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to العربية.
        /// </summary>
        public static string LanguageNameAr {
            get {
                return ResourceManager.GetString("LanguageNameAr", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Français.
        /// </summary>
        public static string LanguageNameFr {
            get {
                return ResourceManager.GetString("LanguageNameFr", resourceCulture);
            }
        }
    }
}
