# CrossBusiness Platform — Roadmap v2 — CANONICAL DATASET, part 2
# OWNER-APPROVED EDITION.
# Screens, phases, dependencies, decisions, risks, and the four execution registers.

SCREEN_FIELDS = ["ScreenId","Category","OwnerPlatformOrModule","Screen","Status","Purpose",
                 "Prerequisites","Permissions","DataSources","Workflow","Reporting","Communication",
                 "MobileRelevance","DesignReference","Evidence"]
def S(*a): return dict(zip(SCREEN_FIELDS, a))

# Existing screen counts are measured from CrossBuy/Views/<folder>/*.cshtml on disk.
SCREENS = [
 # ----- Existing, delivered
 S("SCR-01","Existing","Accounting","Accounting workspace (66 views)","Existing","Ledger, invoicing, statements, assets, closing.","None","Attribute + in-body, 143 debt overall","Accounting entities","Posting and reversal","Statements","None","Low","Legacy - migrate to CrossBusiness Blue via D-37 rollout","Views/Accounting (66)"),
 S("SCR-02","Existing","Inventory and WMS","Inventory workspace (78 views)","Existing","Items, stock, warehouses, counts, pricing, manufacturing, procurement.","None","InventoryAccessService post-B6","Inventory entities","Stock movement","Planned","None","Medium","Legacy - migrate via D-37 rollout","Views/Inventory (78)"),
 S("SCR-03","Existing","CRM","CRM workspace (32 views)","Existing","Accounts, leads, opportunities, custom fields.","None","CrmAccessService - bootstrap-open on unconfigured","Crm entities","Pipeline","Planned","Planned","Medium","Legacy - migrate via D-37 rollout","Views/Crm (32)"),
 S("SCR-04","Existing","HR","Admin and People workspaces (43 views)","Existing","Employees, attendance, leave, appraisals, recruitment, training.","None","HrAccessService","Admin entities","Leave and approval","Planned","Planned","High - attendance","Legacy - migrate via D-37 rollout","Views/Admin (31) + Views/People (12)"),
 S("SCR-05","Existing","POS","POS and PosApp screens (21 views)","Existing","Order capture, payment, KDS, delivery, shift close.","None","PosAccessService","POS entities","Order lifecycle","Planned","None","Core","Domain UX - keeps POS-specific identity","Views/Pos (16) + Views/PosApp (5)"),
 S("SCR-06","Existing","POS","Hypermarket lane (9 views)","Existing","Hyper selling lane, loyalty, receipts.","None","PosAccessService","POS + hyper entities","Pay and void","Hyper sales reports","None","Core","Functional placeholder awaiting owner design","Views/Hyper (9)"),
 S("SCR-07","Existing","Projects","Project workspace (16 views)","Existing","Projects, progress, billing, material, labour.","None","ProjectsAccessService","Project entities","Progress billing","Planned","Planned","Medium","Legacy - migrate via D-37 rollout","Views/Project (16)"),
 S("SCR-08","Existing","Task Management","Tasks screens (5 views)","ExistingWeak","Task list and detail; not an integrated work surface.","None","TasksAccessService","Task entities","Task lifecycle","Planned","Not registered in Comm","High","Assess before change - D-32 approved","Views/Tasks (5)"),
 S("SCR-09","Existing","Calendar","Calendar screen (1 view)","ExistingWeak","Single view; no workspace, no cross-module scheduling.","None","CalendarController","Calendar entities","None","None","Reminder partial","High","Assess before change - D-33 approved","Views/Calendar (1)"),
 S("SCR-10","Existing","Support and Customer Service","Service screens (5 views)","ExistingWeak","Ticket capture and listing; no SLA, no customer visibility.","None","No dedicated access service","Ticket tables","Ticket lifecycle","Planned","Blocked by D-13","Medium","Legacy - migrate via D-37 rollout","Views/Service (5)"),
 S("SCR-11","Existing","Notifications","Notifications screen (1 view)","ExistingWeak","Basic notification list.","None","Session","Notifications","None","None","Superseded by SCR-36","High","Legacy - superseded","Views/Notifications (1)"),
 S("SCR-12","Existing","Files and Document Management","File manager (1 view)","ExistingWeak","Flat file browse; no versioning or control.","None","None dedicated","File tables","None","None","Attachment source","Medium","Legacy - migrate via D-37 rollout","Views/FileManager (1)"),
 S("SCR-13","Existing","Workflow and Approvals","Approvals inbox (1 view)","ExistingWeak","Single inbox view; not a general workflow surface.","None","Partial","Approval tables","Approval","Planned","Planned","High","Superseded by SCR-46","Views/Approvals (1)"),
 S("SCR-14","Existing","Customer Portal","Portal and Store (3 views)","ExistingWeak","Public catalog and portal entry.","None","Public catalog scope","Store tables","Browse","None","None","High","Legacy - migrate via D-37 rollout","Views/Portal (1) + Views/Store (2)"),
 S("SCR-15","Existing","Communication and Collaboration","Legacy Comm screens (3 views)","ExistingWeak","Legacy Comm module UI - NOT the Communication Platform UI.","None","CommunicationAccessService","Comm tables","Message dispatch","None","Legacy path - distinct from COM-01","Medium","Superseded - do not extend","Views/Comm (3)"),
 S("SCR-16","PlatformAdministration","Platform Framework","Business Event Monitor (3 views)","Delivered","Inspect business events and dispatch state. The one delivered platform operational screen.","PLT-02","PlatformOps","BusinessEvents, BusinessEventDispatch","Retry and inspect","Source of the R4 pilot dataset","None","Low","Reference for CrossBusiness Blue admin shell","Views/BusinessEventMonitor (3)"),
 S("SCR-17","Existing","Platform Framework","Platform timeline","Existing","Timeline view over onboarded entities.","PLT-05","Session","Timeline projection","None","None","Timeline surface","Medium","Legacy - migrate via D-37 rollout","Controllers/PlatformTimelineController.cs"),
 S("SCR-18","Existing","Identity and Access","Account screens (5 views)","Existing","Login, profile, password.","None","Anonymous plus session","User tables","Login","None","None","Core","Legacy - migrate via D-37 rollout","Views/Account (5)"),
 S("SCR-19","Existing","Accounting","Currency screens (4 views)","Existing","Currency master and revaluation.","None","Attribute","Currency entities","Revaluation posts reversal","Planned","None","Low","Legacy - migrate via D-37 rollout","Views/Currency (4)"),
 S("SCR-20","Existing","Platform Framework","Announcements and Brand (3 views)","Existing","Announcements banner and brand configuration.","None","Partial","Announcement tables","None","None","Banner in layouts","Low","Legacy - migrate via D-37 rollout","Views/Announcements (1) + Views/Brand (2)"),
 S("SCR-21","Mobile","Mobile and Field Operations","Flutter app (10 screens)","Existing","Mobile client shipping separately from the web host.","IDN-01","API authorization","API controllers","Attendance and lookup","None","Planned","Core","Owner design required","crossbuy_mobile/lib/screens (10)"),
 # ----- CrossBusiness Workspace (R3) — the first integrated user-facing product
 S("SCR-30","Planned","CrossBusiness Workspace","Workspace shell and navigation","Planned","The single front door. Owns no business data; orchestrates approved service contracts.","R1, R2","Session plus every module's own access service - Workspace adds NO permissions","Cross-module read contracts","None of its own","Embedded","Embedded","High","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-44","Planned","CrossBusiness Workspace","My Work","Planned","Unified personal work list drawn from Tasks, approvals and mentions.","SCR-30, TSK-01","Delegated to TasksAccessService and module services","Tasks, approvals, mentions","Read-only aggregation","Saved views","Mentions","High","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-45","Planned","CrossBusiness Workspace","Recent Activity and Timeline","Planned","Cross-module activity from the Communication timeline and business events.","SCR-30, COM-04, PLT-05","Delegated per entity","Timeline projection, BusinessEvents","Read-only","None","Core - Communication owns rendering contract","High","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-46","Planned","CrossBusiness Workspace","Approvals inbox","Planned","Consolidated approvals across modules; replaces the standalone SCR-13.","SCR-30, WFL-01","Delegated to each module's approval authority","Approval tables","Approve and reject via module services","Planned","Notification target","High","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-47","Planned","CrossBusiness Workspace","Saved, recent and favourite reports","Planned","Report shortcuts surfaced in the workspace; execution stays in Report Center.","SCR-30, REP-09","ReportPermissions","Report catalog, favourites","Run via Report Center","Core","None","Medium","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-48","Planned","CrossBusiness Workspace","Quick actions","Planned","Cross-module launch points honouring each module's own permission checks.","SCR-30","Delegated - a hidden control is not a control","Module services","Module workflows","None","None","High","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-49","Planned","CrossBusiness Workspace","Personal dashboard","Planned","Per-user metrics from approved datasets only.","SCR-30, REP-07","Dataset-level authorization","Reporting datasets","None","Core","None","Medium","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-50","Planned","CrossBusiness Workspace","Team dashboard","Planned","Team-scoped metrics; scope resolved by module services, never by the workspace.","SCR-49, OrgHierarchy","Delegated scope resolution","Reporting datasets","None","Core","None","Medium","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-36","Planned","Communication and Collaboration","Mentions and notifications centre","Planned","Unified inbox for mentions and notifications; embedded in the workspace.","COM-08, NOT-01","Session","Comm plus Notifications","None","None","Core","High","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 # ----- Other planned
 S("SCR-31","PlatformAdministration","Core Security","Security Console","Planned","Roles, grants, bootstrap policies, authorization debt burn-down.","SEC-02, SEC-05","PlatformOps","Platform tables","Grant and revoke","Debt report","None","Low","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-32","PlatformAdministration","Master Data","Master Data Console","Planned","Governed master entities and ownership.","MDM-01","PlatformOps","Master entities","Stewardship","Planned","None","Low","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-33","Planned","Reporting Platform","Report Center","Planned","Browse, run, export, schedule and share reports. First dataset: Business Events (D-35).","REP-07","ReportPermissions","Report catalog","Run and schedule","Core","Delivery","Medium","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-34","Planned","Reporting Platform","Report Studio","Planned","Author and edit report definitions and datasets.","REP-07, SCR-33","ReportPermissions.Administer","Dataset registry","Authoring","Core","None","Low","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-35","Planned","Communication and Collaboration","Threads and comments surface","Planned","Universal comment/thread panel embedded in entity screens.","COM-08","CommAccessPolicy","Comm tables","Thread lifecycle","None","Core","High","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-37","Planned","Task Management","Unified Task and Calendar views","Planned","Integrated task and calendar presentation. NOT a new module - integration of existing systems.","TSK-01, CAL-01, SCR-30","TasksAccessService","Task plus Calendar","Task lifecycle","Planned","Mentions","High","Assess existing screens first","No source"),
 S("SCR-38","Planned","Construction and Contracting","Construction workspace","Planned","BOQ, subcontracts, certificates, variations, progress.","CON-04","Project-scoped","Construction tables","Certification","Core","Planned","High - site","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-39","Planned","Construction and Contracting","Site operations and DSR","Planned","Daily site report, RFI, document control.","CON-05","Project-scoped","Construction tables","Site workflow","Core","Core","Core - offline","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-40","Planned","CRM","CRM and Support workspace","Planned","Unified customer view across CRM and Support.","CRM-04, SUP-02","CrmAccessService post-conversion","Crm plus tickets","Case lifecycle","Planned","Core","High","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-41","Planned","Customer Portal","Customer and partner portal","Planned","External self-service portal.","PRT-01, D-29","ExternalPrincipalContext - NOT an employee context","Scoped subset","Self-service","Planned","CustomerVisibleReply only","Core","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-42","Planned","Search","Search surface","Planned","Cross-module search honouring per-module authorization at query time.","SRC-01","Per-module authorization at query time","Search index","None","None","None","High","REQUEST owner Metronic reference - CrossBusiness Blue","No source"),
 S("SCR-43","Planned","Platform Framework","Module dashboards","Planned","Role-based operational dashboards inside module workspaces.","REP-07","Per-module","Datasets","None","Core","None","Medium","REQUEST owner Metronic reference - CrossBusiness Blue","Existing dashboard services only"),
]

PHASE_FIELDS = ["PhaseId","Name","Objective","BusinessValue","Included","Excluded","Prerequisites",
                "Owner","Screens","Services","DatabaseWork","APIWork","SecurityGates","MigrationGates",
                "TestGates","Complexity","ParallelSafety","CompletionCriteria"]
def P(*a): return dict(zip(PHASE_FIELDS, a))

# Complexity uses BANDS (Low / Medium / High / Very High), not calendar estimates.
PHASES = [
 P("R0","Roadmap Reconciliation","Establish one verified account of what exists and freeze an owner-approved plan.","Removes planning based on stale assumptions.","Capability catalog, screen inventory, architectures, registers, decision register, product vision, deployment governance design.","Any production code change.","B6 closed","First Tab","None","None","None","None","No production change","None","Build stays green","Low","Safe - documentation only","COMPLETE after this owner-review increment."),
 P("R1","Repository, Ownership and Deployment Governance","Make the repository committed, owned and deployable before anything is activated.","Every later phase inherits this or inherits its absence.","Commit and preserve current platform work; per-tab worktrees; protected integration branch; tab/shared-file/ADR/SQL-slice registries; canonical SQL root; PlatformSchemaHistory; integration gate; CI validation; stale-build prevention.","Any feature work. Any schema activation.","R0, D-38, D-39, D-40","Integration Owner","None","No new services","Design and apply PlatformSchemaHistory; adopt manifest.json as the authored-slice registry; reconcile the 4 divergent duplicates; resolve the 1 review and 1 not-deployable script","None","No new debt; CBA gates 0/0/0 enforced in CI","Slice inventory reconciled; every applied slice recorded with SHA-256","Full suite green on the integration branch","High","Requires all four tabs to adopt simultaneously","One canonical authored root, an authoritative applied record, integration gate enforced in CI, zero build breaks for one full cadence, all tab work committed."),
 P("R2","Platform Activation Foundation","Controlled activation of the three built-but-dark foundations. No broad UI.","Converts 533 passing tests and 34 tables from zero reach to reachable capability.","Reporting foundation activation; Communication platform activation (Program.cs registration + hosted worker); Construction C1 schema applied in an approved non-production environment; DocComments migration; notification-path reconciliation.","Report Center UI; Communication UI; Workspace; Construction production deployment.","R1, D-05, D-06, D-07, D-19","Integration Owner with Second, Third and Fourth Tabs","None","COM-08 activation; REP-01/02/03 activation","Apply communication slice 001 and reporting slice via the R1 gate; apply Construction C1 DDL in the approved environment only","Activation endpoints only","Every new endpoint attribute- or in-body-secured; debt does not grow","DocComments migration reversible and measured with before/after counts; Construction M3/M9 recorded","221/221 and 274/274 retained plus activation tests","High","Safe once R1 shared-file rules hold","All three foundations reachable in a running environment, migrations measured, one notification path per fact."),
 P("R3","CrossBusiness Workspace Foundation","Deliver the first integrated user-facing product.","The product gains a front door; platform investment becomes visible to users.","Workspace shell and navigation; My Work; notifications and mentions centre; approvals inbox; recent activity and timeline; personal dashboard.","Team dashboard if OrgHierarchy scope is unresolved; Report Studio; module rewrites.","R2","To be assigned","SCR-30, SCR-36, SCR-44, SCR-45, SCR-46, SCR-48, SCR-49","Workspace orchestration only - no new business services","None - Workspace owns no tables","Read-only aggregation contracts","Workspace adds NO permissions; every read delegates to the owning module's access service; hiding a control is not a control","None","Workspace suite plus per-module delegation tests","High","Safe - consumes contracts, owns no module","A user opens one surface and sees their tasks, approvals, mentions and activity across modules, with every item authorized by its owning module."),
 P("R4","Report Center and First Dataset","Bind Reporting to real data and deliver report consumption.","First user-visible return on the reporting investment, at low data sensitivity.","Business Events / Platform Operations pilot dataset (read-only); Report Center; parameters; HTML preview; CSV and Excel; history; archive; saved reports; favourites.","Report Studio; PDF runtime; email delivery; hosted scheduler; any ledger, stock-cost or CRM dataset.","R2, R3, D-35","Second Tab","SCR-33, SCR-47","REP-07, REP-09","Reporting slice already applied in R2","Report APIs","Dataset-level authorization; no sensitive payload exposed by default; row caps enforced","Pilot dataset read-only, no write path","221/221 retained plus dataset and UI tests","High","Safe - Second Tab owns Reporting","The Business Events dataset renders in HTML, CSV and Excel from the Report Center with parameters, history, archive and permissions proved."),
 P("R5","Tasks and Calendar Integration","Integrate two EXISTING systems. Not greenfield.","Turns weak-but-real capability into daily-use capability.","Audit existing Tasks and Calendar implementation; consolidate ownership per D-32/D-33; register Tasks as a Comm entity surface; unified Task/Calendar views; Workspace integration; assess legacy task activity data before migration.","Rebuilding Tasks or Calendar from zero; Support external principal.","R3, D-32, D-33, D-12","To be assigned","SCR-37","TSK-01..05, CAL-01..02, COM-06","Assess the 7 existing task slices and the calendar slice before any schema change","Task and calendar APIs","Task authorization reviewed against the debt list","Legacy task activity assessed before migration; Tasks must not keep a second general timeline","Task and calendar suites plus integration tests","Medium","Safe once Communication is activated","Tasks owns task state and rules; Communication owns comments, mentions and unified timeline; Calendar owns events and presentation; all three visible in one workspace."),
 P("R6","Security Console, CRM Conversion and Master Data","Close the last bootstrap-open exposure behind an operator surface.","Retires the most significant remaining security gap.","CRM B6 conversion (both sites); Security Console; Master Data foundation; authorization debt burn-down start; Support workspace.","AI governance; portal external identity.","R1, D-01, D-02, D-03, D-04, D-31","First Tab","SCR-31, SCR-32, SCR-40","SEC-04, SEC-08, MDM-01, SUP-01","Apply bootstrap policy slice via the R1 gate","Grant and policy APIs","CBA gates stay 0/0/0; debt strictly decreases with reconciliation","Bootstrap policy seed per company","Focused CRM suite plus full suite","High","Safe - First Tab owns these files","Both CRM sites converted with B6-grade evidence, console delivered, debt below 143 and reconciled."),
 P("R7","Construction C2-C8","Deliver the construction platform beyond the commercial foundation.","Closes the assessed gap between Projects and a real construction platform.","WBS, cost codes, budgets, commitments, site operations, DSR, RFI, document control, claims, delays, cash flow, construction UI.","Primavera/MS Project integration; resource levelling.","R2 (C1 schema applied), D-20, D-21, D-24, D-25, D-26","Fourth Tab","SCR-38, SCR-39","CON-05, FIL-02","C2+ slices through the R1 gate","Construction APIs","Project-scoped authorization","M3 and M9 recorded; D-08 default confirmed per company","38/38 retained plus C2+ suites","Very High","Safe - Fourth Tab owns Construction","C1 measured and confirmed; C2-C8 delivered with UI."),
 P("R8","HR and Workforce","Modernise the broadest legacy module set.","HR is wide but shallow and carries significant authorization debt.","HR debt retirement; workflow integration; employee self-service; mobile attendance.","Payroll engine replacement.","R1, R6","To be assigned","HR workspaces","HR-01..HR-07","HR slice review","HR APIs","HR debt retired with evidence","None","HR suites","Medium","Safe","HR actions authorized, self-service delivered, attendance on mobile."),
 P("R9","WMS and Manufacturing Advancement","Advance stock and production beyond transactional basics.","Unlocks warehouse efficiency and production costing.","Advanced WMS (wave picking, putaway, cycle-count planning); manufacturing variance and planning.","Full APS.","R1, D-02","To be assigned","Inventory workspaces","INV-05, MFG-02","WMS slices","Inventory APIs","Warehouse scope enforced post-B6","None","Inventory suites","High","Safe","Wave picking and putaway live; production variance reported."),
 P("R10","Financial Operations Advancement","Deepen accounting beyond posting.","Financial control and compliance.","Generic workflow engine; platform-wide audit; consolidated statements; tax depth.","IFRS reporting packs.","R1, R4, D-01","To be assigned","Accounting workspaces","WFL-02, AUD-03, ACC-07","Accounting slices","Accounting APIs","Accounting debt retired","None","Accounting suites","High","Safe","Approval routing live, audit unified, statements served from the reporting platform."),
 P("R11","Customer and Partner Portals","Extend the platform outside the company.","New service and revenue channel.","ExternalPrincipalContext; portal isolation; self-service; partner access; customer-visible replies.","Payment gateway.","R4, R6, D-13, D-14, D-29","To be assigned","SCR-41","PRT-01, PRT-02, SUP-02","Portal slices","Portal APIs","External principal isolation proved; a customer is never an employee context","None","Portal suites","Very High","Requires the isolation decision first","External users transact under a proved isolation boundary distinct from employee context."),
 P("R12","AI, Search and Automation","Add intelligence over a governed data surface.","Differentiation once the data platform is trustworthy.","Search index; AI governance; assistant surfaces; automation.","Autonomous financial actions.","R4, R10, D-27, D-28","To be assigned","SCR-42","SRC-01, AI-01..AI-03","Search index","AI APIs","AI reads the reporting dataset layer, never raw tables; search honours per-module authorization at query time","None","AI and search suites","High","Safe once governance is decided","Search across modules respects authorization; AI actions governed and audited."),
 P("R13","Industry Packs","Package vertical configurations.","Faster time to value per industry.","Hyper retail pack; contracting pack; services pack.","New core modules.","R7, R9, R10","To be assigned","Pack-specific","Configuration only","Seed data","None","Per-pack authorization review","None","Pack suites","Medium","Safe","Each pack installs as configuration with no core fork."),
 P("R14","Mobile and Field Operations","Deliver a real field client.","Field capture is where the data originates.","Mobile workspace; offline policy; site capture; POS mobility.","Full offline selling.","R5, R7, D-30","To be assigned","SCR-21 expansion","MOB-01, POS-04","Sync schema","Mobile APIs","Mobile authorization equals web authorization","Offline conflict policy proved","Mobile suites","High","Safe","Field users capture offline and sync under a proved conflict policy."),
 P("R15","Ecosystem and Developer Platform","Open the platform to integrators.","Ecosystem leverage.","Integration hub; public API; webhooks; developer documentation.","Marketplace billing.","R12","To be assigned","Developer portal","INT-01","Integration tables","Public API","External API authorization and rate limiting","None","Integration suites","High","Safe","Third parties integrate through a documented, authorized public API."),
]

DEP_FIELDS = ["DependencyId","From","To","Type","Reason"]
def D(*a): return dict(zip(DEP_FIELDS, a))
DEPENDENCIES = [
 D("DEP-01","R1","R0","Sequential","Cannot govern the repository before agreeing what it contains."),
 D("DEP-02","R2","R1","Sequential","No schema is activated until there is an authoritative applied record."),
 D("DEP-03","R3","R2","Sequential","The workspace surfaces platforms that must first be reachable."),
 D("DEP-04","R4","R2","Sequential","Report Center needs the reporting foundation activated."),
 D("DEP-05","R4","R3","Capability","Saved and recent reports surface inside the workspace."),
 D("DEP-06","R5","R3","Capability","Task and calendar views are workspace surfaces."),
 D("DEP-07","R5","R2","Capability","Task comments and timeline require Communication activation."),
 D("DEP-08","R6","R1","Sequential","CRM conversion and the console need a stable integration branch."),
 D("DEP-09","R7","R2","Sequential","C2+ requires the C1 schema applied and measured."),
 D("DEP-10","R8","R6","Capability","HR debt retirement follows the security console."),
 D("DEP-11","R9","R1","Sequential","WMS slices need the canonical SQL root."),
 D("DEP-12","R10","R4","Capability","Financial statements should be served by the reporting platform."),
 D("DEP-13","R11","R4","Capability","Portals need report and document surfaces."),
 D("DEP-14","R11","R6","Capability","Portal customers need the converted CRM and Support model."),
 D("DEP-15","R12","R10","Data","AI needs a governed and audited data surface."),
 D("DEP-16","R12","R4","Data","Search and AI consume the dataset layer."),
 D("DEP-17","R13","R7","Capability","Contracting pack needs construction."),
 D("DEP-18","R13","R9","Capability","Retail pack needs WMS advancement."),
 D("DEP-19","R14","R5","Capability","Mobile work surface mirrors My Work."),
 D("DEP-20","R14","R7","Capability","Site capture is a construction requirement."),
 D("DEP-21","R15","R12","Capability","Public API follows the automation surface."),
 D("DEP-22","R1","D-38","Decision","Canonical SQL root must be chosen before consolidation."),
 D("DEP-23","R1","D-40","Decision","PlatformSchemaHistory design gates the applied record."),
 D("DEP-24","R2","D-05","Decision","Communication activation needs the privacy ceiling."),
 D("DEP-25","R2","D-19","Decision","Construction C1 schema needs an approved environment."),
 D("DEP-26","R4","D-35","Decision","Report Center needs its pilot dataset - APPROVED."),
 D("DEP-27","R5","D-32","Decision","Task ownership - APPROVED."),
 D("DEP-28","R5","D-33","Decision","Calendar ownership - APPROVED."),
 D("DEP-29","R6","D-03","Decision","CRM conversion blocked on customer-data breadth."),
 D("DEP-30","R6","D-04","Decision","CRM conversion blocked on visible-owner scope."),
 D("DEP-31","R11","D-13","Decision","Portals need the external principal model."),
]

DEC_FIELDS = ["DecisionId","Area","Subject","Evidence","Options","Recommendation","Impact",
              "BlockingWork","Owner","DueGate","Status"]
def X(*a): return dict(zip(DEC_FIELDS, a))
DECISIONS = [
 # ---------------- OPEN security decisions (deliberately NOT resolved)
 X("D-01","Security","Accounting.read data breadth","AFTER B6, Accounting.read returns ledger balances with NO branch filter. Exposed: full company trial balance, account values, customer and vendor statements. Affected: every employee of a company with no configured roles, plus every holder of any accounting role. Dimensions available but unused: Company (enforced), Branch (exists, not applied to read), Project (exists via dimensions), Cost centre.","A) keep company-wide unfiltered; B) branch/company-scoped policy; C) role-tiered breadth (summary vs detail); D) separate permission for account values","B - require a branch/company-scoped policy rather than global unfiltered read. A compatibility read should never be broader than the role it replaced.","Changes what an unconfigured company sees and what a low-tier accounting role sees. Compatibility impact: existing role holders may lose cross-branch visibility. Migration: seed a branch-scoped policy per company. Tests: extend the 14 Accounting focused tests with branch dimensions. Screens: 66 Accounting views + 4 Currency views.","R6, R10","Owner","R6 entry","OPEN"),
 X("D-02","Security","Inventory.read warehouse and cost breadth","Inventory.read exposes stock quantities AND unit costs with no branch or warehouse filter, even though B6 site 3 now enforces warehouse scope exactly for CanUseWarehouseAsync. Read and warehouse-scope therefore disagree. Affected: every employee of an unconfigured company; every inventory role holder. Dimensions: Company (enforced), Branch (exists), Warehouse (enforced for use, not for read).","A) keep; B) warehouse/branch-scoped visibility; C) hide cost, show quantity; D) separate stock-cost permission","B plus D - warehouse/branch-scoped visibility AND a separate stock-cost permission. Cost is the sensitive field; quantity usually is not.","Read alignment with the enforced warehouse scope. Compatibility: buyers and clerks may lose cost visibility. Migration: seed scoped policy; introduce a cost permission code. Tests: extend the 8 Inventory focused tests. Screens: 78 Inventory views.","R6, R9","Owner","R6 entry","OPEN"),
 X("D-03","Security","CRM customer-data breadth","CrmAccessService.cs:59 returns TRUE for EVERY CRM action on a company with no configured roles - read, edit, and every other action. Exposed: all accounts, contacts, leads, opportunities, custom field values and bilingual fields. Affected: every authenticated employee of an unconfigured company. Dimensions: Company (enforced), Owner (see D-04), Team (OrgHierarchy exists), Branch.","A) mirror Accounting - read-only compatibility, all other actions Never; B) deny all; C) keep open; D) assigned/team/company policy explicitly selected","D, defaulting to A - require the policy to state assigned, team or company explicitly. The current behaviour is not a policy; it is the absence of one.","Unblocks CRM B6 site 1. Compatibility: unconfigured companies lose edit/delete. Migration: seed a CRM read policy per company. Tests: a CRM focused suite equivalent to the 14 Accounting tests. Screens: 32 Crm views.","R6, R11","Owner","R6 entry","OPEN"),
 X("D-04","Security","CRM unrestricted visible-owner scope","CrmAccessService.cs:98 returns NULL, and null means unrestricted - the widest possible answer, returned precisely when the system knows least. An unconfigured or misconfigured state currently maps SILENTLY to full visibility. Affected: every CRM list and search. Dimensions: Owner, Team via OrgHierarchy, Branch, Company.","A) own records only; B) team scope via OrgHierarchy; C) keep unrestricted; D) distinguish ConfigurationError from Unconfigured and fail closed on both","D then A - an unconfigured or error state must NEVER map silently to unrestricted null. Fail closed, then widen deliberately.","Unblocks CRM B6 site 2. Compatibility: users may lose visibility of records they do not own. Migration: an explicit scope decision per company. Tests: scope-exactness tests mirroring the 10 warehouse tests. Screens: all 32 Crm views.","R6, R11","Owner","R6 entry","OPEN"),
 # ---------------- APPROVED this increment
 X("D-32","Platform","Task Management ownership and boundary","Tasks already has a controller, 5 views, an access service, 7 SQL slices and 2 registered hosted services - it is not greenfield.","A) Tasks owns everything including its own timeline; B) split - Tasks owns state and rules, Communication owns collaboration; C) Communication absorbs Tasks","B - Tasks owns task entity, assignment, status, priority, due dates, dependencies, checklists, subtasks, escalation, time tracking and task-specific rules. Communication owns comments, mentions, attachments, reactions, followers, watchers, unified timeline rendering and notification generation contracts. Tasks PUBLISHES events to the shared timeline and must NOT maintain a second independent general timeline.","Prevents a second timeline implementation. Requires assessment of legacy task activity data before any migration. Work is integration and remediation, NOT greenfield task creation.","R5","Owner","Decided","APPROVED"),
 X("D-33","Platform","Calendar ownership and boundary","Calendar already has a service, controller and SQL slice - it is not greenfield.","A) Calendar owns all scheduling everywhere; B) Calendar owns calendar events and unified presentation only; C) each module owns its own calendar","B - Calendar Platform owns calendar events, recurrence, attendees, meeting metadata, availability, reminders, resource booking, schedule views and external calendar integration contracts. Tasks owns task due dates and task scheduling rules. Projects and Construction own their domain schedules, milestones and activities. Communication owns event comments, mentions and timeline entries. Calendar may DISPLAY tasks but is not their source of truth.","Calendar provides unified presentation and coordination, not ownership of all scheduling data. Requires assessment of the existing service, controller and schema before modification. Do not rebuild from zero.","R5","Owner","Decided","APPROVED"),
 X("D-35","Reporting","First production reporting dataset","No production module is bound as a live dataset. Business Events infrastructure and the Business Event Monitor already exist and are verified.","A) financial statements; B) stock valuation; C) sales analysis; D) Business Events / Platform Operations","D - the Business Events / Platform Operations dataset, READ-ONLY. Lower commercial sensitivity than Accounting, Inventory or CRM; proves the full pipeline (dataset layer, filters, parameters, catalog, HTML, CSV, Excel, history, archive, permissions, row caps) without exposing ledger balances, stock costs or customer data; delivers operational value immediately.","Pilot fields: EventId, EventType, EventVersion, EntityType, EntityId, CompanyId, BranchId where available, OccurredAt, ActorId, CorrelationId, consumer states, failure state, retry count, dispatch timing, non-sensitive operational metadata. Full sensitive payload is NOT exposed by default.","R4","Owner","Decided","APPROVED"),
 X("D-36","Platform","Canonical platform visual identity","crossbuy-brand.css currently overrides Metronic blue with ledger green and gold; CLAUDE.md records the contradiction as open.","A) green and gold; B) CrossBusiness Blue; C) selectable themes","B - CrossBusiness Blue is the canonical platform identity. Platform shell, Workspace, Report Studio, administration consoles, Construction workspace and Communication UI all use blue. Green and gold remain permitted INSIDE financial charts, accounting reports, profit and loss indicators and domain-specific data visualizations - but are not the default shell identity.","All new screens use blue. Existing production UI and crossbuy-brand.css are NOT modified in this increment. Implementation path is D-37.","R3","Owner","Decided","APPROVED"),
 X("D-38","Deployment","Canonical SQL deployment root","Two trees: deploy/sql (57 slices, plus the generated fresh/ build and the operational purge and backup scripts) and CrossBuy/deploy/sql (60 slices, plus manifest.json). The manifest GENERATOR and the schema-history reporter both live at CrossBuy/deploy/. deploy/README.md states the authoritative provisioning method is BACKUP/RESTORE of CrossBuyDB2, not script replay, because EF migrations are broken and ~90 ad-hoc scripts in C:/temp built the schema.","A) deploy/sql canonical; B) CrossBuy/deploy/sql canonical; C) keep both with a manifest; D) a new third root","B - CrossBuy/deploy/sql is the canonical AUTHORED-slice root, because the governance tooling (scan-sql-manifest.ps1, report-schema-history.ps1) and manifest.json already live beside it. deploy/ is retained and RE-LABELLED as the deployment PACKAGE root: generated artifacts (fresh/), operational scripts (backup, purge) and the server README - not an authoring root.","No file is moved or deleted in this increment. Migration of the 55 root-only module slices into the canonical root is an R1 action, executed slice by slice with hash verification.","R1","Owner","R1 entry","APPROVED - migration deferred to R1"),
 X("D-39","Deployment","Divergent same-name slice reconciliation","manifest.json already records 4 duplicateNames with identical=false and distinctHashes=2: pos_hold_recall, pos_order_guests, pos_quickmenu, pos_setup. It also flags 1 script as review (hm16_rename_grni.sql - unguarded, unread, DO NOT DEPLOY) and 1 as not-deployable (script.sql).","A) keep the newer by mtime; B) keep the canonical-root copy; C) diff and merge each pair deliberately; D) supersede both with a new reconciled slice","C then D - each pair is diffed and read by its owner, then superseded by ONE reconciled slice with a new SliceId. Choosing by mtime or by location would be guessing about schema.","Until reconciled, 'apply pos_setup.sql' is ambiguous - the manifest says so explicitly. The review and not-deployable scripts must be resolved or formally excluded before any environment promotion.","R1","Owner","R1 entry","APPROVED - direction"),
 X("D-40","Deployment","PlatformSchemaHistory canonical design","platform_schema_history.sql is authored but applied nowhere, so the table meant to answer 'which slices are applied here' cannot answer it. manifest.json answers the AUTHORED side (115 scripts with SHA-256 and apply rank) but has no database-side counterpart.","A) trust the manifest alone; B) database-side applied record keyed by SliceId + SHA-256; C) external deployment log","B - an applied record in each database: SliceId, filename, SHA-256, module, owner, dependencies, applied date, environment, result. The manifest is the authored registry; PlatformSchemaHistory is the applied registry. Neither replaces the other.","Enables drift detection: missing slice, changed applied slice, duplicate SliceId, same filename with a different hash, out-of-order dependency. Must be the FIRST slice applied in every environment.","R1","Owner","R1 entry","APPROVED - direction"),
 X("D-41","Product","CrossBusiness Workspace as the first integrated product","Three platforms have zero user reach; the product has no unified front door.","A) module-by-module UI improvement; B) a unified workspace as the first product; C) defer any UI until all platforms are activated","B - CrossBusiness Workspace is the first integrated user-facing product. It is NOT a new business module: it owns no Accounting, CRM, Task or Calendar data, orchestrates access through approved service contracts, must never bypass module permissions, uses CrossBusiness Blue, and requires an approved Metronic reference before UI implementation.","Defines R3. Workspace adds no permissions of its own - every read delegates to the owning module's access service.","R3","Owner","Decided","APPROVED"),
 X("D-12","Communication","Unified timeline ownership","Both the platform timeline projection and the Comm aggregator can render activity; Tasks could implement a third.","A) platform timeline canonical; B) Communication aggregator canonical; C) both with one canonical source","B for rendering, with business events as the canonical source of fact - Communication owns unified timeline rendering and notification generation contracts. Modules PUBLISH events; they do not build their own general timelines.","Resolved together with D-32. Tasks must not maintain a second independent general timeline.","R5","Owner","Decided","APPROVED"),
 # ---------------- Approved architecture DIRECTION (not production activation)
 X("D-05","Communication","Privacy ceiling","No maximum visibility is defined for comm content on any entity.","A) global internal-only ceiling; B) per-entity declared ceiling; C) per-thread choice","B - each entity registration DECLARES its maximum visibility. Employee: maximum Internal. Journal Entry: maximum Internal. Invoice: maximum Internal unless an external portal policy exists. Support Ticket: Internal or CustomerVisible by comment type. Public: only for explicitly approved external entities.","Gates Communication activation. Approved as architecture direction; production activation still requires R2.","R2","Owner","R2 entry","APPROVED - architecture direction"),
 X("D-06","Communication","Retention policy","No retention is defined for threads, notifications, attachments or audit.","A) indefinite; B) per-entity declared retention; C) one global period","B - each entity registration declares retention duration, archive behaviour, legal-hold behaviour, deletion/anonymization behaviour and attachment retention.","Gates activation and audit. Approved as architecture direction.","R2","Owner","R2 entry","APPROVED - architecture direction"),
 X("D-07","Communication","Per-entity audit policy","CommAuditWriter exists but per-entity policy is undefined.","A) audit everything; B) audit sensitive entities; C) per-entity declaration","C - each entity registration declares edit-history, deletion-history, read-receipt, attachment-audit and immutable-history requirements.","Gates the DocComments migration. Approved as architecture direction.","R2","Owner","R2 entry","APPROVED - architecture direction"),
 X("D-13","Communication","Support external-principal model","No model exists for a customer participating in a thread; a customer is currently representable only as an employee BusinessContext, which would be wrong.","A) no external participation; B) mirrored portal identity; C) a distinct ExternalPrincipalContext","C - a customer must NOT be treated as an employee BusinessContext. Requires a future ExternalPrincipalContext ADR before any implementation.","Support must NOT be activated until this exists. Approved as architecture direction only.","R11","Owner","R11 entry","APPROVED - architecture direction, ADR required"),
 X("D-14","Communication","Customer-visible comments","No distinction exists between internal notes and customer-facing replies.","A) never customer-visible; B) explicit per comment; C) per thread","B - two explicit comment types: InternalNote and CustomerVisibleReply. Explicit and auditable per comment.","Gates portal support. Approved as architecture direction.","R11","Owner","R11 entry","APPROVED - architecture direction"),
 X("D-15","Communication","@Role reverse membership resolution","Mention by role requires reverse role-to-user resolution, which no component owns.","A) platform role directory; B) per-module; C) cached projection","A - the platform role directory already exists and is the natural owner.","@Role mentions remain BLOCKED until reverse role-membership lookup exists.","R2","Owner","R2 entry","BLOCKED - pending implementation"),
 # ---------------- Open: reporting operations
 X("D-09","Reporting","PDF runtime owner","PlaywrightPdfReportRenderer exists in code; no runtime is provisioned.","A) Playwright in-host; B) sidecar service; C) third-party service","B - a sidecar keeps a browser runtime out of the web host.","Gates PDF export. Not required for the R4 pilot, which ships HTML, CSV and Excel.","R4+","Owner","Post-R4","OPEN"),
 X("D-10","Reporting","Email delivery integration","ReportDelivery has no transport.","A) reuse Communication channels; B) direct SMTP; C) provider API","A - one delivery path for the product, not two.","Gates scheduled delivery. Depends on Communication activation.","R4+","Owner","Post-R4","OPEN"),
 X("D-11","Reporting","Hosted scheduler ownership","ReportScheduleService has no hosted worker.","A) a new dedicated hosted worker; B) extend the dispatch worker; C) external scheduler","A - a distinct worker with its own scope, matching the platform rule that a hosted service takes IServiceScopeFactory and scopes per run.","Gates scheduling. Not required for the R4 pilot.","R4+","Owner","Post-R4","OPEN"),
 X("D-16","Reporting","SQL vocabulary CHECK constraints","Reporting vocabulary is not constrained in SQL.","A) add CHECK constraints; B) enforce in code only; C) both","B - a second copy of a vocabulary drifts, and it drifts in the dangerous direction. This is why the 15 Never-bootstrap-open actions were deliberately NOT duplicated as a CHECK constraint.","Schema hardening.","R4","Owner","R4 entry","OPEN"),
 X("D-17","Reporting","Report Studio sequence","Whether authoring precedes or follows consumption.","A) Report Center first; B) Studio first; C) together","A - consumption before authoring. R4 delivers the Center; Studio follows.","Sequencing only.","R4","Owner","R4 entry","OPEN"),
 # ---------------- Open: construction
 X("D-19","Construction","DDL rollout environment","construction_c1 DDL (8 tables) is authored and applied nowhere, while the C1 services ARE registered in Program.cs.","A) a dedicated non-production environment; B) shared dev; C) a production window","A - an approved non-production environment. The measurement must not run against shifting data.","Gates R2 construction activation and all of R7. No SQL executed in this increment.","R2, R7","Owner","R2 entry","OPEN"),
 X("D-20","Construction","M3 and M9 measurement result","The measurement script has not been run.","Measure, then decide","Run the script in the D-19 environment. Stop automatically if M3 > 0, per the existing rule.","Gates C2 scope definition.","R7","Owner","R7 entry","OPEN"),
 X("D-21","Construction","D-08 default mode per company","The default commercial policy mode per company is unconfirmed. Modes: Warning, ApprovalRequired, HardBlock.","A) Warning; B) ApprovalRequired; C) HardBlock; D) per-company explicit with no default","B - ApprovalRequired for unconfigured companies: safer than Warning, less operationally disruptive than HardBlock, and it requires explicit authority for overspend.","RECOMMENDATION ONLY - not approved. A silent default is how bootstrap-open happened.","R7","Owner","R7 entry","OPEN - recommendation recorded"),
 X("D-24","Construction","Satellite-table consolidation timing","When to consolidate construction satellite tables.","A) before C2; B) during C4; C) never","A - consolidating after features are built on the current shape is far more expensive.","Schema shape.","R7","Owner","R7 entry","OPEN"),
 X("D-25","Construction","C6 approval and C7 variation reroute","Header-only subcontract approval enforcement and the live VariationOrderService approval reroute are deferred.","A) as assessed - C6 and C7; B) earlier; C) later","A - as already assessed.","Sequencing.","R7","Owner","R7 entry","OPEN"),
 X("D-26","Construction","Legacy concurrency strategy","Five legacy base tables lack concurrency control.","A) rowversion on all five; B) optimistic checks in services; C) accept the risk","A - the C1 work already proved the pattern.","Data integrity under concurrent commercial edits.","R7","Owner","R7 entry","OPEN"),
 # ---------------- Open: platform
 X("D-23","Security","Inventory.purchase action split","One action gates a PO draft, a goods receipt (creates stock) and a PO-to-invoice conversion (accounting effect) - three impact classes, one permission code.","A) keep closed whole; B) split into three codes; C) split into two","B eventually - the single code cannot express three impacts. Kept closed whole for now, with the VOCABULARY DEFECT reason pinned by test so the decision cannot be reversed silently.","Permission vocabulary.","R6, R9","Owner","R6 entry","OPEN - closed whole for now"),
 X("D-27","Platform","AI governance","AiService and AiInsightsService exist with NO AI-specific authorization, behind a context that still has 143 unprotected actions.","A) governed dataset-only access; B) full read; C) disable until governed","A - AI reads the reporting dataset layer, never raw tables.","Gates all AI work.","R12","Owner","R12 entry","OPEN"),
 X("D-28","Platform","Search ownership","No search implementation exists; zero source files match.","A) platform-owned index; B) per-module search; C) external engine","A - one index that honours per-module authorization AT QUERY TIME, not by filtering after retrieval.","Gates search.","R12","Owner","R12 entry","OPEN"),
 X("D-29","Platform","Client portal isolation","The portal currently uses the constrained public catalog scope only.","A) extend the public scope; B) a dedicated ExternalPrincipalContext; C) a separate application","B - an external user is not an employee with fewer rights. Aligns with D-13.","Gates portals.","R11","Owner","R11 entry","OPEN"),
 X("D-30","Platform","Mobile and offline policy","No agreed offline capability or conflict policy beyond POS sync.","A) read-only offline; B) capture offline, sync online; C) full offline","B - matches the POS sync precedent without introducing offline selling.","Gates mobile.","R14","Owner","R14 entry","OPEN"),
 X("D-31","Platform","Master Data ownership","No owner for master entities shared across modules: Employee, Customer, Item, Supplier.","A) a platform-owned MDM; B) the originating module owns; C) per-entity ownership with a register","C - those four entities have genuinely different natural owners; a single MDM owner would be a fiction.","Gates Master Data work.","R6","Owner","R6 entry","OPEN"),
 X("D-37","Platform","BRAND-IMPLEMENTATION - legacy CSS migration","crossbuy-brand.css globally overrides Metronic blue with green and gold; 327 existing views render under it. D-36 makes blue canonical but changes no CSS.","A) replace the current global green override now; B) apply blue to new screens first, then migrate legacy pages through an approved visual rollout; C) support selectable themes; D) retain legacy pages until individually redesigned","B - apply CrossBusiness Blue to all NEW screens first, then migrate legacy pages through an approved visual rollout. A global override flip would restyle 327 views at once with no design review.","Do NOT modify crossbuy-brand.css, existing production UI or CLAUDE.md in this increment. Specialized operational screens (POS, KDS, hyper lane, mobile attendance, storefront) keep their domain UX.","R3+","Owner","R3 entry","OPEN"),
]

RISK_FIELDS = ["RiskId","Area","Risk","Evidence","Severity","Likelihood","Impact","Mitigation","Owner","Status"]
def RK(*a): return dict(zip(RISK_FIELDS, a))
RISKS = [
 RK("RSK-01","Deployment","Two SQL trees with divergent same-name slices","deploy/sql (57) and CrossBuy/deploy/sql (60); 4 filenames in both, all 4 differ, 0 identical. manifest.json already records all 4 with identical=false and distinctHashes=2.","High","Certain","'Apply pos_setup.sql' is ambiguous - the manifest states this explicitly.","D-38 names a canonical root; D-39 reconciles each pair deliberately in R1. No file moved in this increment.","Integration Owner","Open - governed by R1"),
 RK("RSK-02","Deployment","No authoritative APPLIED record","platform_schema_history.sql is authored but applied nowhere. manifest.json answers the AUTHORED side (115 scripts, SHA-256, apply rank) but has no database-side counterpart.","High","Certain","No reliable answer to 'which slices are applied to this database'.","D-40: PlatformSchemaHistory as the applied registry, first slice in every environment.","Integration Owner","Open - governed by R1"),
 RK("RSK-21","Deployment","An unreviewed script is in the tree","manifest.json classifies hm16_rename_grni.sql as 'review' - a mutating batch with no re-run guard that nobody has read - and script.sql as 'not-deployable'.","High","Certain","A re-run could mutate data unguarded, or a deployment could include a script judged unsafe.","Resolve or formally exclude both before any environment promotion (R1).","Integration Owner","Open"),
 RK("RSK-22","Deployment","Provisioning does not use the slices at all","deploy/README.md states the authoritative way to stand up the schema is BACKUP/RESTORE of CrossBuyDB2, because EF migrations are broken and ~90 ad-hoc scripts in C:/temp built the schema - a third source outside the repository.","High","Certain","The slice registry describes a build path that is not the one actually used; a fresh environment may not match any manifest state.","R1 must reconcile the restore-based path with the slice registry and decide which is authoritative for new environments.","Integration Owner","Open"),
 RK("RSK-03","Security","143 unprotected mutating actions","Analyzer baseline, shrink-only, enforced at build.","High","Certain","Unauthorized mutation across 143 actions.","Burn down in R6 and R8; analyzer keeps it shrink-only.","First Tab","Open"),
 RK("RSK-04","Security","CRM bootstrap-open remains","CrmAccessService.cs:59 returns true for every action; :98 returns null (unrestricted).","High","Certain","Full CRM access and unrestricted visibility on any unconfigured company.","Convert in R6 once D-03 and D-04 are decided.","First Tab","Open"),
 RK("RSK-05","Process","Shared-tree build breaks","Five cross-tab breaks from three tabs during Stage 2A.","High","Likely","Acceptance runs on stale binaries; false green results.","R1 execution model; no tab may leave the integration branch unbuildable.","All tabs","Open - governed by R1"),
 RK("RSK-06","Process","Uncommitted parallel work","git ls-files returns empty for the entire Platform tree.","High","Certain","Every tab's base shifts invisibly.","Commit all four tabs in R1.","All tabs","Open - governed by R1"),
 RK("RSK-07","Reporting","Foundation with no consumer","221/221 tests, 12 tables, zero production datasets, zero screens.","Medium","Certain","Investment does not convert to value; drift from real data shapes.","R2 activation then R4 pilot dataset (D-35 approved).","Second Tab","Open - governed by R2/R4"),
 RK("RSK-08","Communication","Foundation not activated","274/274 tests; CommunicationPlatformRegistration not called in Program.cs; no hosted worker.","Medium","Certain","A complete platform nobody can use.","R2 activation behind D-05/D-06/D-07.","Third Tab","Open - governed by R2"),
 RK("RSK-09","Communication","Two comment models coexist","Legacy DocCommentService plus the Comm platform.","Medium","Certain","Divergent comment history; migration cost grows.","DocComments migration in R2 with before/after counts.","Third Tab","Open - governed by R2"),
 RK("RSK-10","Communication","Two notification paths","Legacy NotifyAsync plus the projection consumer; a path bypassing the outbox was observed.","Medium","Likely","Duplicate or divergent notifications.","Reconcile during R2 activation - one fact, one notification.","Third Tab","Open - governed by R2"),
 RK("RSK-11","Construction","Services registered against tables that do not exist","C1 services are in Program.cs; construction_c1 DDL is applied nowhere.","High","Certain","A construction code path can fail at runtime on a missing table.","Apply DDL in the D-19 environment during R2.","Fourth Tab","Open - governed by R2"),
 RK("RSK-12","Construction","Legacy concurrency gap","Five legacy base tables lack concurrency control.","Medium","Likely","Lost updates on concurrent commercial edits.","Adopt the C1 rowversion pattern in R7 (D-26).","Fourth Tab","Open"),
 RK("RSK-13","Platform","Unowned modules with live workers","Tasks has 2 registered hosted services and no owner; Calendar has a live service and no owner.","Medium","Certain","Changes land with no owner and no review.","RESOLVED by D-32 and D-33; assignment to a tab is an R1 action.","Owner","Mitigated - ownership decided"),
 RK("RSK-14","Platform","Kernel is a hard runtime dependency","RecordAsync has no swallowing catch; ReverseAsync depends on BusinessEvents.","High","Certain","A missing table fails a real sale or any correction.","Every platform slice applied and verified before each phase.","Integration Owner","Mitigated by process"),
 RK("RSK-15","Platform","Background paths and BusinessContext","The kernel requires a signed-in context; a new background writer would throw.","Medium","Possible","A future background document writer fails in production.","Covered by the DI wiring test; re-checked on every new hosted service.","Integration Owner","Open"),
 RK("RSK-16","Security","PlatformOps via accounting fallback","PlatformOpsAttribute falls back to Accounting.manage.","Low","Rare","Platform operations granted through an accounting role.","Closed - Accounting.manage is Never-bootstrap-open, asserted directly.","First Tab","Closed"),
 RK("RSK-17","Quality","Stale-build false green","Mutation H first passed against a stale assembly under --no-build.","High","Likely","Evidence that proves nothing.","Capture the build error count explicitly; never --no-build for mutation evidence.","All tabs","Mitigated by rule"),
 RK("RSK-18","Product","Three platforms with no user reach","Reporting, Communication and Construction C1: 533 tests, 34 tables, 0 screens.","Medium","Certain","Stakeholders may believe features exist.","Catalog separates CurrentStatus from ProductionActivation and UIStatus; R2-R4 convert them.","Owner","Mitigated by disclosure"),
 RK("RSK-19","Security","AI over ungoverned data","AI services exist with no AI-specific authorization; no search exists.","Medium","Possible","AI surfaces data a user may not access.","Route AI through the reporting dataset layer (D-27).","Owner","Open"),
 RK("RSK-20","Data","Master data has no owner","No MDM; Employee, Customer, Item and Supplier shared informally.","Medium","Certain","Duplicate and divergent master records.","Per-entity ownership register in R6 (D-31).","Owner","Open"),
 RK("RSK-23","Product","Workspace could become a permission bypass","A unified surface aggregating cross-module data is the classic place for an authorization shortcut.","High","Possible","One aggregated query could return data the user cannot see in the owning module.","D-41: Workspace adds NO permissions; every read delegates to the owning module's access service. Per-module delegation tests are an R3 gate.","To be assigned","Open - designed against"),
 RK("RSK-24","Product","Brand divergence between spec and code","D-36 makes CrossBusiness Blue canonical while crossbuy-brand.css globally overrides to green and gold across 327 views.","Medium","Certain","New and legacy screens look like two products.","D-37 rollout: blue on new screens first, legacy migrated through an approved visual rollout.","Owner","Open"),
]

TAB_FIELDS = ["TabId","Tab","Scope","OwnedPaths","MayNotTouch","IntegrationCadence","Status"]
def T(*a): return dict(zip(TAB_FIELDS, a))
TABS = [
 T("TAB-1","First Tab - Core Security and Platform Governance","Authorization, bootstrap policy, grants, analyzer, security console.","CrossBuy.Analyzers/**; CrossBuy.Analyzers.Tests/**; CrossBuy/BL/Platform/Bootstrap*; CrossBuy/BL/Platform/PlatformGrant*; CrossBuy/BL/Platform/Timeline*; CrossBuy/BL/*AccessService.cs; CrossBuy/Models/Platform/Bootstrap*; CrossBuy/Models/Platform/PlatformGrant*; CrossBuy/Models/Context/Platform/BootstrapAccessPolicy.cs; CrossBuy/Models/Context/Platform/PlatformRoleAssignment.cs; CrossBuy/Controllers/Api/PlatformGrantsApiController.cs; engineering/**; docs/platform/Stage-002A-*; docs/roadmap-v2/**; CrossBuy/CrossBuy.csproj; CrossBuy.sln; CrossBuy/Resources/**; CrossBuy/Views/Shared/**; CrossBuy/deploy/**; deploy/**; governance/**; .github/workflows/**; docs/platform/ADR-*; docs/deployment/**; CrossBuy/BL/Platform/**; CrossBuy/Models/Platform/**; CrossBuy/Models/Context/Platform/**; CrossBuy/BL/IntegrityCheckHostedService.cs; CrossBuy/BL/CrmReminderHostedService.cs; CrossBuy.Tests/WriterWorkerGovernanceTests.cs; CrossBuy.Tests/EntityConversationPartialContractTests.cs","Reporting, Communication, Construction trees","Daily","Active - B6 closed"),
 T("TAB-2","Second Tab - Reporting Platform","Reporting engine, datasets, exporters, Report Center and Studio.","CrossBuy/BL/Reporting/**; CrossBuy/Models/Context/Reporting/**; CrossBuy/Controllers/Api/ReportsCenterApiController.cs; CrossBuy/Views/Reports*/**; CrossBuy/deploy/sql/reporting_platform.sql; docs/platform/ADR-037*","Security, Communication, Construction trees","Daily","Active - foundation complete, activation in R2"),
 T("TAB-3","Third Tab - Communication and Collaboration","Comm platform, threads, mentions, notifications, timeline.","CrossBuy/BL/Communication/**; CrossBuy/BL/Comm/**; CrossBuy/Models/Context/Communication/**; CrossBuy/Models/Context/Comm/**; CrossBuy/Models/Communication/**; CrossBuy/deploy/sql/communication_platform_slice_001.sql; CrossBuy/deploy/sql/comm_*; docs/platform/ADR-03[0-6]*; CrossBuy/BL/ChatService.cs; CrossBuy/Controllers/ChatController.cs; CrossBuy/Hubs/ChatHub.cs; CrossBuy/Views/Chat/**; CrossBuy/Resources/Views/Chat/**; CrossBuy/Models/Context/Chat/**; CrossBuy/deploy/sql/comm_chat_*.sql; CrossBuy/Hubs/ChatHub.cs; CrossBuy/Hubs/NotificationsHub.cs; CrossBuy.Tests/Communication/QuotationConversationTests.cs","Security, Reporting, Construction trees","Daily","Active - foundation complete, activation in R2"),
 T("TAB-4","Fourth Tab - Construction and Contracting","BOQ, subcontracts, commercial revisions, construction C2-C8.","CrossBuy/BL/Construction/**; CrossBuy/BL/BoqService.cs; CrossBuy/BL/SubcontractBillingService.cs; CrossBuy/BL/VariationOrderService.cs; CrossBuy/Models/Context/Construction/**; deploy/sql/construction_c1_*; docs/construction/**","Security, Reporting, Communication trees","Daily","Active - C1 verified, DDL applied nowhere"),
 T("TAB-5","Tasks and Calendar - UNASSIGNED","Task state and rules; calendar events and unified presentation.","CrossBuy/BL/TaskService.cs; CrossBuy/BL/TasksAccessService.cs; CrossBuy/BL/TaskGeneratorHostedService.cs; CrossBuy/BL/TaskScheduleMatchHostedService.cs; CrossBuy/BL/CalendarService.cs; CrossBuy/Controllers/TasksController.cs; CrossBuy/Controllers/CalendarController.cs; CrossBuy/BL/TasksCalendar/**; CrossBuy/Views/Tasks/**; CrossBuy/Views/Calendar/**; CrossBuy/deploy/sql/tasks_*; CrossBuy/deploy/sql/calendar.sql","Other tabs' trees","Daily once assigned","UNASSIGNED - 2 live hosted services with no owner (R1 action)"),
 T("TAB-6","CrossBusiness Workspace","Workspace shell, My Work, approvals, mentions and activity surfaces (R3). APPOINTED NARROWLY for the read-only cross-silo approval inbox: aggregation, read DTOs, navigation metadata and Workspace consumption. Approval WRITES (approve/reject/post/release/confirm/escalate) stay with the module services.","CrossBuy/BL/Workspace/**; CrossBuy/Controllers/WorkspaceController.cs; CrossBuy/Views/Workspace/**; CrossBuy/BL/Approvals/**; CrossBuy/Controllers/ApprovalsController.cs; CrossBuy/Views/Approvals/**; CrossBuy/BL/ApprovalInboxDto.cs; CrossBuy/Controllers/ProjectController.cs; CrossBuy/BL/ProjectMembershipService.cs; CrossBuy/Models/Context/Accounting/ProjectMember.cs; CrossBuy/Views/Project/Team.cshtml; CrossBuy.Tests/Projects*Tests.cs","Other tabs' trees; approval WRITE paths in module services","Daily","APPOINTED for read-only approval inbox (owner ruling); wider Workspace R3 scope still unassigned"),
]

SHARED_FIELDS = ["FileId","File","Owner","ChangeRule","Reason"]
def SF(*a): return dict(zip(SHARED_FIELDS, a))
SHARED_FILES = [
 SF("SHF-01","CrossBuy/Program.cs","Integration Owner","Append inside the tab's own marked region only; ONE registration extension method per platform; never reorder another tab's block.","Every tab registers services; unmarked edits collide on every change. AddCrossBusinessReporting is the pattern."),
 SF("SHF-02","CrossBuy/Models/Context/CrossDbContext.cs","Integration Owner","Add DbSets in the tab's marked region; never reorder; never reformat.","245 DbSets; whole-file edits guarantee conflicts."),
 SF("SHF-03","CrossBuy/CrossBuy.csproj","Integration Owner","Package and analyzer references by request only.","A reference change alters every tab's build."),
 SF("SHF-04","CrossBuy.sln","Integration Owner","Project additions by request only.","Project GUIDs conflict destructively."),
 SF("SHF-05","CrossBuy/Resources/SharedResources*.resx","Integration Owner","Our keys only via git plumbing; never whole-file git add.","Files are reordered by other work; whole-file staging loses keys."),
 SF("SHF-06","CrossBuy/Views/Shared/_Layout*.cshtml","Integration Owner","Partial insertion by request; the partial must exist or every screen breaks.","Shared layouts already embed cross-tab partials."),
 SF("SHF-07","CrossBuy/deploy/sql/** (CANONICAL authored root)","Integration Owner","Claim a SliceId in the registry before authoring; regenerate manifest.json via scan-sql-manifest.ps1.","D-38 names this the canonical authored root; the manifest tooling lives beside it."),
 SF("SHF-08","deploy/** (deployment PACKAGE root)","Integration Owner","Generated artifacts and operational scripts only - NOT an authoring root after D-38.","deploy/sql/fresh is generated by gen_fresh_db.ps1; backup and purge are operational."),
 SF("SHF-09","CrossBuy/deploy/sql/manifest.json","Integration Owner","Never hand-edit; regenerate with scan-sql-manifest.ps1.","The file says so itself; a hand-edit desynchronises hashes from content."),
 SF("SHF-10","docs/platform/ADR-*.md","Integration Owner","Reserve the number in the ADR registry before writing.","ADR numbers are sparse; collisions are silent."),
 SF("SHF-11","CrossBuy/wwwroot/css/crossbuy-brand.css","Integration Owner","FROZEN in this increment. Changes only through the D-37 approved visual rollout.","A global override flip would restyle 327 views with no design review."),
 SF("SHF-12","CrossBuy/BL/JournalEntryService.cs","Architectural invariant - owner coordination required","No change without pre-coordination with the owner.","The single GL writer; already kernel-wired once without coordination."),
 SF("SHF-13","CrossBuy/BL/StockService.cs","Architectural invariant - owner coordination required","No change without pre-coordination with the owner.","The single stock writer."),
 SF("SHF-14","CrossBuy/BL/LeaveWorkflowService.cs","Module workflow - TAB-6 narrow read handoff","TAB-6 may ADD read-only pending-approval readers only. The approver chain, CreateAsync, DecideAsync, approval-step writes, notifications and escalation are module-owned and must not change.","Carries the leave approver company boundary (87ec8fa). A read contract is needed by the cross-silo inbox, but the workflow itself is not TAB-6's to alter."),
 SF("SHF-15","CrossBuy/BL/EmployeeRequestService.cs","Module workflow - TAB-6 narrow read handoff","TAB-6 may ADD read-only pending-approval readers only. CreateAsync, DecideAsync, workflow transitions, approval writes and notification logic are module-owned and must not change.","Shares the approver chain with leave, including its defect guard. Same narrow read need, same restriction."),
 SF("SHF-16","governance/registry/**","Integration Owner - approved shared governance infrastructure","Never hand-edit. Change the canonical dataset in docs/roadmap-v2/_generator and regenerate; every edit needs explicit owner approval (-AllowShared) and must preserve machine-enforced ownership semantics.","These registries ARE the ownership rules the checker reads. TAB-1 owns governance/** as integration owner, but shared is evaluated BEFORE ownership, so keeping them shared forces an explicit approval on every edit instead of letting the tab that owns the rules change the rules unremarked."),
 SF("SHF-17","governance/tools/**","Integration Owner - approved shared governance infrastructure","Changes require explicit owner approval (-AllowShared) and must not weaken the ownership checker or its exit codes.","The enforcement tooling itself. A tab that could silently relax check-file-ownership.ps1 could grant itself any path."),
 SF("SHF-18","CrossBuy/BL/Platform/BusinessEventService.cs","Architectural invariant - owner coordination required","No change without pre-coordination with the owner.","The single outbox writer; the per-consumer fan-out is decided here, so one edit changes what every consumer ever sees."),
 SF("SHF-19","CrossBuy/Controllers/AccountingController.cs","Module surface - integration owner unblock only","Company-context remediation of named read paths only. No posting, stock, journal, receivable or payment behaviour may change under this entry.","Invoice read paths still resolve company from a compile-time constant while the product surface above them is company-scoped; the legacy business modules have no tab, so the screens cannot be fixed by their owner."),
 SF("SHF-20","CrossBuy/Views/Shared/_DocEventTimeline.cshtml","Integration Owner - shared document partial","Shared by three committed document views; changes require owner approval (-AllowShared).","Three committed views include this partial and it was never committed, so a clean checkout throws partial-not-found on both invoice detail screens and the work order screen."),
 SF("SHF-21","CrossBuy/Views/Shared/_DocTimeline.cshtml","Integration Owner - shared document partial","Shared document comments widget; changes require owner approval (-AllowShared).","The committed Inventory/QuotationDetails view includes this partial and it was never committed, so a clean checkout throws partial-not-found on the quotation screen."),
 SF("SHF-22","CrossBuy/deploy/sql/project_members.sql","Integration Owner - deployment slice","Schema slice for a table committed product code queries; changes require owner approval (-AllowShared).","ProjectsAccessService queries dbo.ProjectMembers but the DDL that creates it was never committed, so a fresh deployment has no such table."),
 SF("SHF-23","CrossBuy/Views/Accounting/SalesInvoiceDetail.cshtml","Integration Owner - shared conversation caller","Includes the shared _EntityConversation panel and must name its own two conversation endpoints; the partial resolves none on a caller's behalf. Accounting feature work and Platform contract changes both land here, so changes require owner approval (-AllowShared).","The conversation endpoints used to be hardcoded inside the shared partial as Url.Action of an Accounting action, so any second module including it posted to the Accounting controller. Moving them to the caller binds this view to a shared platform contract that a tab other than the Accounting owner maintains."),
 SF("SHF-24","CrossBuy/Views/Accounting/PurchaseInvoiceDetail.cshtml","Integration Owner - shared conversation caller","Includes the shared _EntityConversation panel and must name its own two conversation endpoints; the partial resolves none on a caller's behalf. Accounting feature work and Platform contract changes both land here, so changes require owner approval (-AllowShared).","The conversation endpoints used to be hardcoded inside the shared partial as Url.Action of an Accounting action, so any second module including it posted to the Accounting controller. Moving them to the caller binds this view to a shared platform contract that a tab other than the Accounting owner maintains."),
 SF("SHF-25","CrossBuy/Views/Inventory/QuotationDetails.cshtml","Integration Owner - shared conversation caller","Includes the shared _EntityConversation panel and must name its own two conversation endpoints; the partial resolves none on a caller's behalf. Inventory feature work and Platform contract changes both land here, so changes require owner approval (-AllowShared).","Same contract as SHF-23/24 on the invoice views. This screen was the last one rendering the legacy _DocTimeline widget into DocComments; converging it onto the Communication Platform binds an Inventory view to a shared platform contract that the Inventory owner does not maintain."),
 SF("SHF-26","CrossBuy/Controllers/InventoryController.cs","Module surface - conversation endpoints only","Communication conversation endpoints for Inventory-owned documents only (QuotationConversation, QuotationConversationAdd) and their shared gate. No stock, pricing, procurement, warehouse, approval or costing behaviour may change under this entry.","The quotation conversation must be authorized by the module that owns the document rather than routed through AccountingController, so the endpoints live here; but the file is the Inventory module surface and is not TAB-3 work. Narrow entry mirroring SHF-19 rather than transferring a 2900-line controller."),
]

ADR_FIELDS = ["AdrId","Title","Area","Owner","Status"]
def A(*a): return dict(zip(ADR_FIELDS, a))
ADRS = [
 A("ADR-001","Transactional Business Events","Platform Kernel","Platform","Accepted"),
 A("ADR-002","Entity Registry","Platform Kernel","Platform","Accepted"),
 A("ADR-003","Dispatch State Per Consumer","Platform Kernel","Platform","Accepted"),
 A("ADR-004","Business Event Visibility","Platform Kernel","Platform","Accepted"),
 A("ADR-005","Legacy Timeline Adapters","Platform Kernel","Platform","Accepted"),
 A("ADR-006","Notification Projection","Platform Kernel","Platform","Accepted"),
 A("ADR-007","SQL Server Dispatch Locking","Platform Kernel","Platform","Accepted"),
 A("ADR-008","Operator Dispatch Retry","Platform Kernel","Platform","Accepted"),
 A("ADR-009","Platform Operations Authorization","Core Security","First Tab","Accepted"),
 A("ADR-010","Session-Free Permission Evaluation","Core Security","First Tab","Accepted"),
 A("ADR-011","RESERVED - unused","-","Integration Owner","Available"),
 A("ADR-012","Deployment Manifest and Schema History","Deployment","Integration Owner","Accepted - superseded in part by ADR-039"),
 A("ADR-013","Single Worker Process","Platform Kernel","Platform","Accepted"),
 A("ADR-014","RESERVED - unused","-","Integration Owner","Available"),
 A("ADR-015","RESERVED - unused","-","Integration Owner","Available"),
 A("ADR-016","Reproducible Architecture Evidence","Governance","First Tab","Accepted"),
 A("ADR-017","RESERVED - unused","-","Integration Owner","Available"),
 A("ADR-018","RESERVED - unused","-","Integration Owner","Available"),
 A("ADR-019","RESERVED - unused","-","Integration Owner","Available"),
 A("ADR-020","RESERVED - unused","-","Integration Owner","Available"),
 A("ADR-021","RESERVED - unused","-","Integration Owner","Available"),
 A("ADR-022","BusinessContext Resolution Policy","Core Security","First Tab","Accepted"),
 A("ADR-023","Company Isolation Bypass","Core Security","First Tab","Accepted"),
 A("ADR-024","Pilot Company Isolation","Core Security","First Tab","Accepted"),
 A("ADR-025","Accounting API Security Policy","Core Security","First Tab","Accepted"),
 A("ADR-026","Shared Platform RBAC","Core Security","First Tab","Accepted"),
 A("ADR-027","HR Permission Model","Core Security","First Tab","Accepted"),
 A("ADR-028","Projects Permission Model","Core Security","First Tab","Accepted"),
 A("ADR-029","Tasks and Communication Permission Models","Core Security","First Tab","Accepted"),
 A("ADR-030","Communication Platform Architecture","Communication","Third Tab","Accepted - RETAINED"),
 A("ADR-031","Universal Collaboration Surface","Communication","Third Tab","Accepted - RETAINED"),
 A("ADR-032","Mention Resolution","Communication","Third Tab","Accepted - RETAINED"),
 A("ADR-033","Communication Visibility and Thread Permissions","Communication","Third Tab","Accepted - RETAINED"),
 A("ADR-034","Notification Channels, Templates, Preferences","Communication","Third Tab","Accepted - RETAINED"),
 A("ADR-035","Comment History, Soft Delete, Audit","Communication","Third Tab","Accepted - RETAINED"),
 A("ADR-036","Timeline Aggregation","Communication","Third Tab","Accepted - RETAINED"),
 A("ADR-037","Reporting Platform Architecture","Reporting","Second Tab","Accepted - CONFIRMED as the Reporting ADR"),
 A("ADR-038","RESERVED - Parallel execution model (worktrees + integration branch)","Governance","Integration Owner","Reserved for R1"),
 A("ADR-039","RESERVED - Canonical SQL root and PlatformSchemaHistory","Deployment","Integration Owner","Reserved for R1"),
 A("ADR-040","RESERVED - Master Data ownership register","Master Data","Integration Owner","Reserved for R6"),
 A("ADR-041","RESERVED - ExternalPrincipalContext","Core Security","First Tab","Reserved for R11 - required by D-13"),
 A("ADR-042","RESERVED - CrossBusiness Workspace architecture and delegation rule","Product","To be assigned","Reserved for R3"),
 A("ADR-043","RESERVED - CrossBusiness Blue visual identity and rollout","Product","Integration Owner","Reserved for R3 - required by D-36/D-37"),
 A("ADR-044","RESERVED - Entity registration declarations (privacy, retention, audit)","Communication","Third Tab","Reserved for R2 - required by D-05/D-06/D-07"),
]

SLICE_FIELDS = ["SliceId","Slice","Tree","Owner","AppliedStatus","GatesOurPath","Note"]
def SL(*a): return dict(zip(SLICE_FIELDS, a))
SQL_SLICES = [
 SL("SQL-01","platform_business_events.sql","CANONICAL (CrossBuy/deploy/sql)","Platform","Applied on acceptance DB","Yes - sale, purchase, reversal","Missing causes SQL-208 on a real sale."),
 SL("SQL-02","platform_business_events_slice_002.sql","CANONICAL","Platform","Applied on acceptance DB","Yes","Notifications.EntityType/EntityId; missing causes SQL-207. Apply with sqlcmd -I."),
 SL("SQL-03","platform_role_assignments.sql","CANONICAL","First Tab","Authored","No","Batch A grant storage."),
 SL("SQL-04","platform_role_assignments_slice_002.sql","CANONICAL","First Tab","Authored","No","Batch A extension."),
 SL("SQL-05","bootstrap_access_policies.sql","CANONICAL","First Tab","Authored - NOT applied","No","B6 policy store; 6 CHECKs, filtered unique index, drift detection. Applies in R6."),
 SL("SQL-06","reporting_platform.sql","CANONICAL","Second Tab","A0 - deployed via the pipeline and recorded in PlatformSchemaHistory (probe-verified); NOT applied to CrossBuyDB2","No","12 tables. Deployed with apply-sql-slices.ps1 -Slice, which validates a named slice on the same terms as the global pre-flight so an unrelated backlog cannot block a clean one. Applied hash matches the manifest exactly."),
 SL("SQL-07","communication_platform_slice_001.sql","CANONICAL","Third Tab","Authored - NOT applied","No","14 tables; from-empty and idempotency proved. Applies in R2."),
 SL("SQL-08","comm_outbox_slice_003.sql","CANONICAL","Third Tab","Authored","No","Legacy Comm module outbox - distinct from the Communication Platform."),
 SL("SQL-09","platform_schema_history.sql","CANONICAL","Integration Owner","Authored - NOT applied","No","RSK-02. D-40 makes this the APPLIED registry and the first slice in every environment."),
 SL("SQL-10","construction_c1_commercial_foundation.sql","PACKAGE (deploy/sql)","Fourth Tab","Authored - NOT applied","No","8 tables. Applies in R2 in the D-19 environment only. Migrates to canonical root in R1."),
 SL("SQL-11","construction_c1_contract_mapping_measurement.sql","PACKAGE","Fourth Tab","Authored - NOT applied","No","M3/M9 measurement script. Run in R2 after SQL-10."),
 SL("SQL-12","pos_hold_recall.sql","BOTH - DIVERGENT","POS owner","Unknown","No","manifest.json: identical=false, distinctHashes=2. Reconcile per D-39."),
 SL("SQL-13","pos_order_guests.sql","BOTH - DIVERGENT","POS owner","Unknown","No","manifest.json: identical=false, distinctHashes=2. Reconcile per D-39."),
 SL("SQL-14","pos_quickmenu.sql","BOTH - DIVERGENT","POS owner","Unknown","No","manifest.json: identical=false, distinctHashes=2. Reconcile per D-39."),
 SL("SQL-15","pos_setup.sql","BOTH - DIVERGENT","POS owner","Unknown","No","manifest.json: identical=false, distinctHashes=2. Reconcile per D-39."),
 SL("SQL-16","hm16_rename_grni.sql","CANONICAL","Hyper track","Unknown","No","manifest.json idempotency = REVIEW: a mutating batch with no re-run guard that nobody has read. DO NOT DEPLOY until resolved (RSK-21)."),
 SL("SQL-17","script.sql","REPOSITORY ROOT","Unknown","Never","No","manifest.json idempotency = NOT-DEPLOYABLE and excludedFromDeploy. Judged unsafe to re-run."),
 SL("SQL-18","00_backup_dev_db.sql","PACKAGE","Integration Owner","Operational","No","excludedFromDeploy - operational, not a schema slice."),
 SL("SQL-19","10_purge_for_production.sql","PACKAGE","Integration Owner","Operational","No","excludedFromDeploy - run once after restore."),
 SL("SQL-20","deploy/sql/fresh/*.sql","PACKAGE - GENERATED","Integration Owner","Generated by gen_fresh_db.ps1","No","Generated schema build; not hand-authored. Confirms deploy/ is the package root, not an authoring root."),
 SL("SQL-21","(53 further module slices, package tree only)","PACKAGE","Various","Various","No","HR, CRM, projects, pricing, manufacturing, notifications, announcements, chat, boq, brand. Migrate to canonical root in R1 with hash verification."),
 SL("SQL-22","(50 further module slices, canonical tree only)","CANONICAL","Various","Various","Some","Hyper (hm*), POS, tasks (7 slices), calendar, library, inventory reconcile."),
]

# manifest.json summary — the AUTHORED-side registry that already exists.
MANIFEST_FACTS = {
    "generator": "CrossBuy/deploy/scan-sql-manifest.ps1",
    "manifest": "CrossBuy/deploy/sql/manifest.json",
    "totalScripts": 115,
    "guarded": 92, "guardedByPredicate": 7, "review": 1,
    "notDeployable": 1, "noMutation": 14, "excluded": 3,
    "duplicateNames": 4, "duplicateNamesIdentical": 0,
    "perScriptFields": "path, name, bytes, encoding, sha256, rank, guards, mutations, "
                       "unguardedBatches, idempotency, reviewVerdict, reviewEvidence, "
                       "excludedFromDeploy, excludedReason",
}
